### ISSUE TITLE
QWen 1.8B can't run 8k input after fused qkv

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/ipex-llm#10536]
https://github.com/intel-analytics/ipex-llm/pull/10368
Using 0324 version, for 8k input, get error:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arda/kai/BigDL/python/llm/dev/benchmark/all-in-one/run.py", line 52, in run_model_in_thread
    output_ids = model.generate(input_ids, do_sample=False, max_new_tokens=out_len,
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/arda/kai/BigDL/python/llm/dev/benchmark/all-in-one/../benchmark_util.py", line 1563, in generate
    return self.greedy_search(
  File "/home/arda/kai/BigDL/python/llm/dev/benchmark/all-in-one/../benchmark_util.py", line 2385, in greedy_search
    outputs = self(
  File "/home/arda/kai/BigDL/python/llm/dev/benchmark/all-in-one/../benchmark_util.py", line 533, in __call__
    return self.model(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arda/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 1045, in forward
    transformer_outputs = self.transformer(
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/bigdl/llm/transformers/models/qwen.py", line 708, in qwen_model_forward
    outputs = block(
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/arda/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 612, in forward
    attn_outputs = self.attn(
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/bigdl/llm/transformers/models/qwen.py", line 106, in qwen_attention_forward
    return forward_function(
  File "/opt/anaconda3/envs/kai-llm-pip/lib/python3.9/site-packages/bigdl/llm/transformers/models/qwen.py", line 149, in qwen_attention_forward_original
    position_ids = self.position_ids[kv_seq_len]
IndexError: index 8192 is out of bounds for dimension 0 with size 8192
```
Using 0311 version can run 8192 input successfully.

**Comment by qiuxin2012** [comment]
QWen 1.8B's "max_position_embeddings" is 8192, I will fix it.
