### ISSUE TITLE
LangChain-Chatchat ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by ywang30intel** [intel-analytics/ipex-llm#10574]
Using Knowledge base QA, exception will be generated if no matching at all, shown as following:
![image](https://github.com/intel-analytics/ipex-llm/assets/21199573/92279519-f742-4a93-9308-aeb8e7957c48)

to reproduce the issue, use question e.g. "what is China"
on host side, exception in ASGI:

2024-03-27 19:43:44,303 - _client.py[line:1027] - INFO: HTTP Request: GET http://127.0.0.1:7861/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
INFO:     127.0.0.1:42054 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2024-03-27 19:43:44,821 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ywang30/miniconda3/envs/bigdl-langchain-chatchat/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/ywang30/miniconda3/envs/bigdl-langchain-chatchat/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/ywang30/miniconda3/envs/bigdl-langchain-chatchat/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/ywang30/miniconda3/envs/bigdl-langchain-chatchat/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 568, in receive
    await self.message_event.wait()
  File "/home/ywang30/miniconda3/envs/bigdl-langchain-chatchat/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fed6c14a690

During handling of the above exception, another exception occurred:

**Comment by Oscilloscope98** [comment]
Hi @ywang30intel,

We are working on it, and will let you know when the bug is fixed.

**Comment by Oscilloscope98** [comment]
Hi @ywang30intel,

This bug has been fixed. :) You could update your code base with [new configuration files](https://github.com/intel-analytics/Langchain-Chatchat/tree/ipex-llm/configs) and have a try again. Tipycally, you will just need to `python copy_config_example.py` again with config files in our updated code, and use the old Python env.

Please let us know for any further problems :)
