### ISSUE TITLE
RecursionError at get_peft_model when using lora/qlora

### ISSUE THREAD

**Issue by Aloereed** [intel-analytics/ipex-llm#10600]
qlora_finetuning.py is the file in qlora example folder.
Model is Chinese-llama-2 or qwen-1.8B
```
2024-03-31 16:49:06,782 - INFO - Converting the current model to nf4 format......
Traceback (most recent call last):
  File "d:\AI\qlora\qlora_finetuning.py", line 99, in <module>
    model = get_peft_model(model, config)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\ipex_llm\transformers\qlora.py", line 282, in get_peft_model
    model = get_peft_model_original(*args, **kwargs)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\mapping.py", line 136, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\peft_model.py", line 1094, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\peft_model.py", line 129, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\lora\model.py", line 136, in __init__
    super().__init__(model, config, adapter_name)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 148, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 325, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\lora\model.py", line 220, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\ipex_llm\transformers\qlora.py", line 224, in _create_new_module
    new_module = LoraLowBitLinear(adapter_name,
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\ipex_llm\transformers\qlora.py", line 78, in __init__
    LowBitLinear.__init__(
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\ipex_llm\transformers\low_bit_linear.py", line 520, in __init__
    super().__init__(input_features, output_features, bias)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\torch\nn\modules\module.py", line 1712, in __setattr__
    self.register_parameter(name, value)
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\torch\nn\modules\module.py", line 577, in register_parameter
    elif hasattr(self, name) and name not in self._parameters:
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 439, in weight
    weight = base_layer.weight
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 439, in weight
    weight = base_layer.weight
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 439, in weight
    weight = base_layer.weight
  [Previous line repeated 974 more times]
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 433, in weight
    base_layer = self.get_base_layer()
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\peft\tuners\tuners_utils.py", line 422, in get_base_layer
    while hasattr(base_layer, "base_layer"):
  File "c:\Users\user\miniconda3\envs\qlora\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by plusbang** [comment]
Hi, according to your log, it seems that you are using a high version `peft`.
Please install `peft==0.5.0` following [our install guide](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/LLM-Finetuning/QLoRA/alpaca-qlora#1-install).

**Comment by Aloereed** [comment]
Solved! Thank you
