### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.Qwen-7B-Chat-Int4'

### ISSUE THREAD

**Issue by ChenVkl** [intel-analytics/ipex-llm#10616]
I encountered a 'module not found' error when using the Qwen-7b int4 model. What could be the issue? How can I resolve it?
The following is a detailed description of error messages.

19:37:07-244095 INFO     Loading Qwen-7B-Chat-Int4
19:37:07-248588 ERROR    Failed to load the model.
Traceback (most recent call last):
  File "D:\workspace\text-generation-webui-bigdl-llm\modules\ui_model_menu.py", line 233, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
  File "D:\workspace\text-generation-webui-bigdl-llm\modules\models.py", line 88, in load_model
    output = load_func_map[loader](model_name)
  File "D:\workspace\text-generation-webui-bigdl-llm\modules\models.py", line 330, in bigdl_llm_loader
    config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code)
  File "C:\Users\ZhangChen\.conda\envs\llm\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1091, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "C:\Users\ZhangChen\.conda\envs\llm\lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\ZhangChen\.conda\envs\llm\lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Users\ZhangChen\.conda\envs\llm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.Qwen-7B-Chat-Int4'

<img width="1243" alt="1" src="https://github.com/intel-analytics/ipex-llm/assets/165237083/7896f9c6-2e7c-46e1-bfae-2db0d4703da8">

**Comment by hkvision** [comment]
I suppose currently we only support loading the original Qwen model instead of the int4 model directly.

**Comment by ChenVkl** [comment]
> I suppose currently we only support loading the original Qwen model instead of the int4 model directly.

What method do I need to use if I want to load the int4 model with Qwen-7b? Are there any relevant tutorials or articles that I can refer to. Thank you very much for your help.

**Comment by ChenVkl** [comment]
> I suppose currently we only support loading the original Qwen model instead of the int4 model directly.

I am currently trying to run the Qwen-7b int4 model on A750 in a BigDL environment, but it still cannot be loaded. I am very distressed and would appreciate it if you could help me.

**Comment by jason-dai** [comment]
> > I suppose currently we only support loading the original Qwen model instead of the int4 model directly.
> 
> What method do I need to use if I want to load the int4 model with Qwen-7b? Are there any relevant tutorials or articles that I can refer to. Thank you very much for your help.

https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model

**Comment by hkvision** [comment]
> > I suppose currently we only support loading the original Qwen model instead of the int4 model directly.
> 
> What method do I need to use if I want to load the int4 model with Qwen-7b? Are there any relevant tutorials or articles that I can refer to. Thank you very much for your help.

We only support the original fp16 model and then we convert to int4 in runtime and put it on Arc GPU. I think we can continue with this issue: https://github.com/intel-analytics/ipex-llm/issues/10575

**Comment by hkvision** [comment]
Closing this issue, will continue the support in https://github.com/intel-analytics/ipex-llm/issues/10575

**Comment by ChenVkl** [comment]
> > > I suppose currently we only support loading the original Qwen model instead of the int4 model directly.
> > 
> > 
> > What method do I need to use if I want to load the int4 model with Qwen-7b? Are there any relevant tutorials or articles that I can refer to. Thank you very much for your help.
> 
> https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/HF-Transformers-AutoModels/Model

Thank you very much, I'll give it a try.
