### ISSUE TITLE
failed to run truthfulqa_mc1 by harness

### ISSUE THREAD

**Issue by aoke79** [intel-analytics/ipex-llm#11015]
Traceback (most recent call last):
  File "c:\aigc\llama\ipex-llm\python\llm\dev\benchmark\harness\lm-evaluation-harness\lm_eval\tasks\__init__.py", line 369, in get_task
    return TASK_REGISTRY[task_name]
           ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'truthfulqa_mc1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AIGC\llama\ipex-llm\python\llm\dev\benchmark\harness\run_llb.py", line 150, in <module>
    main()
  File "C:\AIGC\llama\ipex-llm\python\llm\dev\benchmark\harness\run_llb.py", line 102, in main
    results = evaluator.simple_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\aigc\llama\ipex-llm\python\llm\dev\benchmark\harness\lm-evaluation-harness\lm_eval\utils.py", line 243, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\aigc\llama\ipex-llm\python\llm\dev\benchmark\harness\lm-evaluation-harness\lm_eval\evaluator.py", line 89, in simple_evaluate
    task_dict = lm_eval.tasks.get_task_dict(tasks)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\aigc\llama\ipex-llm\python\llm\dev\benchmark\harness\lm-evaluation-harness\lm_eval\tasks\__init__.py", line 390, in get_task_dict
    task_name_dict = {
                     ^
  File "c:\aigc\llama\ipex-llm\python\llm\dev\benchmark\harness\lm-evaluation-harness\lm_eval\tasks\__init__.py", line 391, in <dictcomp>
    task_name: get_task(task_name)()
               ^^^^^^^^^^^^^^^^^^^
  File "c:\aigc\llama\ipex-llm\python\llm\dev\benchmark\harness\lm-evaluation-harness\lm_eval\tasks\__init__.py", line 373, in get_task
    raise KeyError(f"Missing task {task_name}")
KeyError: 'Missing task truthfulqa_mc1'

(env_p311) C:\AIGC\llama\ipex-llm\python\llm\dev\benchmark\harness>

**Comment by hkvision** [comment]
Please note that truthfulqa is the task name and mc1 is the metrics. You should use input `truthfulqa` instead of truthfulqa_mc1.

The trutufulqa task will output metrics mc1 and mc2. Huggingface leaderboard https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard, it uses mc2 as the final metrics. If you choose mc1, you may not compare with the scores in the leaderboard.
![image](https://github.com/intel-analytics/ipex-llm/assets/21994046/553ce318-af0a-4370-bcbc-24d33d79cab2)

**Comment by Edward-Lin** [comment]
fixed, thanks a lot.
but how to close it?
