### ISSUE TITLE
[qwen2][windows][MTL]  6-8k input token OOM

### ISSUE THREAD

**Issue by juan-OY** [intel-analytics/ipex-llm#11284]
Qwen2 input token 6800, output token 512 OOM       

已经去掉如下操作   C:\ProgramData\miniconda3\envs\qwen1.5\Lib\site-packages\transformers\models\qwen2\modeling_qwen2.py
#logits = logits.float()

报错
                                                                                                                                                                                      
Traceback (most recent call last):
  File "D:\ultra_test_code_and_data\benchmark_test2intel\speed_test_ultra-qwen27b.py", line 270, in <module>
    infer_test(model, tokenizer, input_token_num, output_token_num, total_speed_file)
  File "D:\ultra_test_code_and_data\benchmark_test2intel\speed_test_ultra-qwen27b.py", line 108, in infer_test
    prefill_output = model(**model_inputs)
  File "C:\Users\seewo\miniforge3\envs\qwen2\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\seewo\miniforge3\envs\qwen2\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\seewo\miniforge3\envs\qwen2\lib\site-packages\transformers\models\qwen2\modeling_qwen2.py", line 1186, in forward
    logits = self.lm_head(hidden_states)
  File "C:\Users\seewo\miniforge3\envs\qwen2\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\seewo\miniforge3\envs\qwen2\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\seewo\miniforge3\envs\qwen2\lib\site-packages\ipex_llm\transformers\low_bit_linear.py", line 737, in forward
    result = xe_linear.forward_new(x_2d, self.weight.data, self.weight.qtype,
RuntimeError: Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)

**Comment by lalalapotter** [comment]
Synced with user offline, cannot reproduce in our env, will check in users' env later.

**Comment by lalalapotter** [comment]
This issue is because auto import PR https://github.com/intel-analytics/ipex-llm/pull/11227, already revert in latest nightly version. Please try latest nightly version or use `set BIGDL_IMPORT_IPEX=0` and `import intel_extension_for_pytorch as ipex`.

**Comment by juan-OY** [comment]
We can close, the issue is resolved after upgrading to latest nightly build eg 0612
