### ISSUE TITLE
run GLM4-9b-chat on MTL iGPU get error: pyo3_runtime.PanicException: index out of bounds:

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#11308]
log:
```
python test_glm.py
C:\Users\mi\miniforge3\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\mi\miniforge3\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-06-13 17:12:09,748 - INFO - intel_extension_for_pytorch auto imported
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\regex-1.8.1\src\dfa.rs:1415:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "D:\LLM\test_glm.py", line 12, in <module>
    inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\glm-4-9b-chat\tokenization_chatglm.py", line 211, in apply_chat_template
    result = handle_single_conversation(conversation)
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\glm-4-9b-chat\tokenization_chatglm.py", line 191, in handle_single_conversation
    input = self.build_single_message(
  File "C:\Users\mi\.cache\huggingface\modules\transformers_modules\glm-4-9b-chat\tokenization_chatglm.py", line 136, in build_single_message
    role_tokens = [self.convert_tokens_to_ids(f"<|{role}|>")] + self.tokenizer.encode(f"{metadata}\n",
  File "C:\Users\mi\AppData\Roaming\Python\Python310\site-packages\tiktoken\core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
pyo3_runtime.PanicException: index out of bounds: the len is 1 but the index is 1
```

test_glm.py:
```
import torch
from transformers import AutoTokenizer
from ipex_llm.transformers import AutoModelForCausalLM
import intel_extension_for_pytorch as ipex

device = "xpu"

tokenizer = AutoTokenizer.from_pretrained("./models/glm-4-9b-chat",trust_remote_code=True)

query = "你好"

inputs = tokenizer.apply_chat_template([{"role": "user", "content": query}],
                                       add_generation_prompt=True,
                                       tokenize=True,
                                       return_tensors="pt",
                                       return_dict=True
                                       )

inputs = inputs.to(device)
model = AutoModelForCausalLM.from_pretrained(
    "./models/glm-4-9b-chat",
    # torch_dtype=torch.bfloat16,
    load_in_low_bit="sym_int4",
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    use_cache=True,
).to(device).eval()

gen_kwargs = {"max_length": 2500, "do_sample": True, "top_k": 1}
with torch.no_grad():
    outputs = model.generate(**inputs, **gen_kwargs)
    outputs = outputs[:, inputs['input_ids'].shape[1]:]
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))
```

version:
```
(base) D:\LLM>pip list 
transformers                4.36.2    note: 4.37.1 also get the same error.
ipex-llm                    2.1.0b20240612
bigdl-core-xe-21            2.5.0b20240612
bigdl-core-xe-addons-21     2.5.0b20240612
```

**Comment by qiuxin2012** [comment]
The error is throw by tiktoken, I just tried some different versions. I found if tiktoken version <= 0.4.0, I will get the same error.
You can update tiktoken to 0.7.0.

**Comment by violet17** [comment]
> The error is thrown by tiktoken, I just tried some different versions. I found if tiktoken version <= 0.4.0, I will get the same error. You can upgrade tiktoken to 0.7.0.

After upgrade tiktoken to 0.7.0, I can run glm-4-9b successfully. Thanks.
