### ISSUE TITLE
ImportError: undefined symbol: iJIT_NotifyEvent on 2-ARC GPU

### ISSUE THREAD

**Issue by raj-ritu17** [intel-analytics/ipex-llm#11409]
Trying to do inference on arc GPU machine, have followed this guidelines:

```
https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Pipeline-Parallel-Inference 
and  run_mistral_arc_2_card.sh
```

```
(llm) :~/xxx/ipex-llm/python/llm/example/GPU/Pipeline-Parallel-Inference$ bash run_llama_arc_2_card.sh

:: WARNING: setvars.sh has already been run. Skipping re-execution.
   To force a re-execution of setvars.sh, use the '--force' option.
   Using '--force' can result in excessive use of your environment variables.

usage: source setvars.sh [--force] [--config=file] [--help] [...]
  --force        Force setvars.sh to re-run, doing so may overload environment.
  --config=file  Customize env vars using a setvars.sh configuration file.
  --help         Display this help message and exit.
  ...            Additional args are passed to individual env/vars.sh scripts
                 and should follow this script's arguments.

  Some POSIX shells do not accept command-line options. In that case, you can pass
  command-line options via the SETVARS_ARGS environment variable. For example:

  $ SETVARS_ARGS="ia32 --config=config.txt" ; export SETVARS_ARGS
  $ . path/to/setvars.sh

  The SETVARS_ARGS environment variable is cleared on exiting setvars.sh.

Traceback (most recent call last):
  File "/home/rajritu/miniforge3/envs/llm/bin/torchrun", line 5, in <module>
    from torch.distributed.run import main
  File "/home/rajritu/miniforge3/envs/llm/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/xxxx/miniforge3/envs/llm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

**Comment by qiuxin2012** [comment]
Please run the ENV-Check script in https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts, and share the outputs to us.
The error is thrown by torch, can you run 1 card inference?
