### ISSUE TITLE
Run Llama-2-7B-Chat-hf bigdl_ipex_bf16 Error on Xeon SPR

### ISSUE THREAD

**Issue by biyuehuang** [intel-analytics/ipex-llm#11469]
ipex-llm/python/dev/benchmark/all-in-one/run-srp.sh

Run Llama-2-7B-Chat-hf bigdl_ipex_bf16 Error on Intel(R) Xeon(R) w9-3475X

config.yaml
```
repo_id:
  # - 'THUDM/chatglm2-6b'
  - 'meta-llama/Llama-2-7B-Chat-hf'
  # - 'liuhaotian/llava-v1.5-7b' # requires a LLAVA_REPO_DIR env variables pointing to the llava dir; added only for gpu win related test_api now
local_model_hub: '/home/12900/llm-models/'
warm_up: 1 # must set >=2 when run "pipeline_parallel_gpu" test_api
num_trials: 3
num_beams: 1 # default to greedy search
low_bit: 'sym_int4' # default to use 'sym_int4' (i.e. symmetric int4)
batch_size: 1 # default to 1
in_out_pairs:
  - '1024-512'
 # - '1024-128'
test_api:
   - "bigdl_ipex_bf16"                     # on Intel CPU, (qtype=bf16)
  # - "bigdl_ipex_int4"                     # on Intel CPU, (qtype=int4)
  # - "bigdl_ipex_int8"                     # on Intel CPU, (qtype=int8)
  # - "speculative_cpu"                     # on Intel CPU, inference with self-speculative decoding
  # - "deepspeed_transformer_int4_cpu"      # on Intel CPU, deepspeed autotp inference
cpu_embedding: False # whether put embedding to CPU
streaming: False # whether output in streaming way (only available now for gpu win related test_api)
use_fp16_torch_dtype: True # whether use fp16 for non-linear layer (only available now for "pipeline_parallel_gpu" test_api)
task: 'continuation' # task can be 'continuation', 'QA' and 'summarize'
```

```
$ pip list
Package                     Version
--------------------------- --------------
accelerate                  0.23.0
annotated-types             0.7.0
antlr4-python3-runtime      4.9.3
certifi                     2024.6.2
charset-normalizer          3.3.2
filelock                    3.15.4
fsspec                      2024.6.1
huggingface-hub             0.23.4
idna                        3.7
intel-cmplr-lib-ur          2024.2.0
intel-extension-for-pytorch 2.3.0
intel-openmp                2024.2.0
ipex-llm                    2.1.0b20240629
Jinja2                      3.1.4
MarkupSafe                  2.1.5
mpmath                      1.3.0
networkx                    3.3
numpy                       1.26.4
omegaconf                   2.3.0
packaging                   24.1
pandas                      2.2.2
pillow                      10.3.0
pip                         24.0
protobuf                    5.27.2
psutil                      6.0.0
py-cpuinfo                  9.0.0
pydantic                    2.7.4
pydantic_core               2.18.4
python-dateutil             2.9.0.post0
pytz                        2024.1
PyYAML                      6.0.2rc1
regex                       2024.5.15
requests                    2.32.3
safetensors                 0.4.3
sentencepiece               0.2.0
setuptools                  69.5.1
six                         1.16.0
some-package                0.1
sympy                       1.12.1
tabulate                    0.9.0
tokenizers                  0.15.2
torch                       2.3.1+cpu
torchaudio                  2.3.1+cpu
torchvision                 0.18.1+cpu
tqdm                        4.66.4
transformers                4.37.0
triton                      2.3.1
typing_extensions           4.12.2
tzdata                      2024.1
urllib3                     2.2.2
wheel                       0.43.0
```

```
all-in-one$ ./run-spr.sh 
found intel-openmp in /home/12900/miniconda3/envs/llm/lib/libiomp5.so
found tcmalloc in /home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/libs/libtcmalloc.so
+++++ Env Variables +++++
Internal:
    ENABLE_IOMP     = 1
    ENABLE_GPU      = 0
    ENABLE_JEMALLOC = 0
    ENABLE_TCMALLOC = 1
    LIB_DIR    = /home/12900/miniconda3/envs/llm/lib
    BIN_DIR    = /home/12900/miniconda3/envs/llm/bin
    LLM_DIR    = /home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm

Exported:
    LD_PRELOAD             = /home/12900/miniconda3/envs/llm/lib/libiomp5.so /home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/libs/libtcmalloc.so
    OMP_NUM_THREADS        = 36
    MALLOC_CONF            = 
    USE_XETLA              = 
    ENABLE_SDP_FUSION      = 
    SYCL_CACHE_PERSISTENT  = 
    BIGDL_LLM_XMX_DISABLED = 
    SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS = 
+++++++++++++++++++++++++
Complete.
Loading checkpoint shards: 100%|█████████████████| 2/2 [00:00<00:00,  2.86it/s]
2024-06-30 21:07:13,664 - INFO - Converting the current model to bf16 format......
[INFO] SINGLE_INSTANCE MODE.
2024-06-30 21:07:22,597 - INFO - Conv BatchNorm folding failed during the optimize process.
2024-06-30 21:07:22,601 - INFO - Linear BatchNorm folding failed during the optimize process.
Traceback (most recent call last):
  File "/home/12900/llm-models/all-in-one/./run.py", line 1871, in <module>
    run_model(model, api, in_out_pairs, conf['local_model_hub'], conf['warm_up'], conf['num_trials'], conf['num_beams'],
  File "/home/12900/llm-models/all-in-one/./run.py", line 143, in run_model
    result = run_bigdl_ipex_bf16(repo_id, local_model_hub, in_out_pairs, warm_up, num_trials, num_beams, batch_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/llm-models/all-in-one/./run.py", line 1288, in run_bigdl_ipex_bf16
    model = AutoModelForCausalLM.from_pretrained(model_path, load_in_low_bit='bf16', trust_remote_code=True, torch_dtype=torch.bfloat16,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/unittest/mock.py", line 1378, in patched
    return func(*newargs, **newkeywargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/model.py", line 351, in from_pretrained
    model = cls.load_convert(q_k, optimize_model, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/model.py", line 503, in load_convert
    model = ggml_convert_low_bit(model, qtype, optimize_model,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/convert.py", line 792, in ggml_convert_low_bit
    model = _optimize_ipex(model, qtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/convert.py", line 934, in _optimize_ipex
    model = _ipex_optimize_model(model, rms_classes, qtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/convert_ipex.py", line 149, in _ipex_optimize_model
    _ipex_optimize_rmsnorm(model, rms_classes, is_tpp=is_tpp, is_woq=is_woq)
  File "/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/convert_ipex.py", line 55, in _ipex_optimize_rmsnorm
    from intel_extension_for_pytorch.transformers.models.cpu.fusions.mha_fusion import _IPEXRMSNorm
ImportError: cannot import name '_IPEXRMSNorm' from 'intel_extension_for_pytorch.transformers.models.cpu.fusions.mha_fusion' (/home/12900/miniconda3/envs/llm/lib/python3.11/site-packages/intel_extension_for_pytorch/transformers/models/cpu/fusions/mha_fusion.py)
```

**Comment by hzjane** [comment]
This issue may be caused by the 2.3.0 version of intel-extension-for-pytorch. We now only support 2.2.0 on bigdl_ipex_bf16, you can refer to [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/CPU/Speculative-Decoding/Self-Speculation/llama2#4-accelerate-with-bigdl_opt_ipex) to install libs and try again.

**Comment by biyuehuang** [comment]
Thanks. It worked.

```
pip install torch==2.2.0+cpu torchvision==0.17.0+cpu torchaudio==2.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html -i https://pypi.tuna.tsinghua.edu.cn/simple some-package

pip install intel-extension-for-pytorch==2.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple some-package --trusted-host pypi.tuna.tsinghua.edu.cn
pip install oneccl_bind_pt==2.2.0 --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/cpu/us/
```
