### ISSUE TITLE
MiniCPM-Llama3-V-2_5 can't run on A770 Ubuntu. 

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/ipex-llm#11667]
oneapi 2024.0, Ubuntu22.04, A770

```
#Model Download
from modelscope import snapshot_download
model_dir = snapshot_download('OpenBMB/MiniCPM-Llama3-V-2_5')

import torch
from PIL import Image
from ipex_llm.transformers import AutoModel
#from transformers import AutoModel
from transformers import AutoTokenizer

model_path = "./models/MiniCPM-Llama3-V-2_5"

#model = AutoModel.from_pretrained(model_path, trust_remote_code=True, torch_dtype=torch.bfloat16)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True, load_in_low_bit="sym_int4")
# model = AutoModel.from_pretrained(model_path, trust_remote_code=True, load_in_low_bit="sym_int4", modules_to_not_convert=["vpm", "resampler"])

#model = model.float()

model.to('xpu')
model.eval()
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)


image = Image.open('./test_image/guo.png').convert('RGB')
question = 'What is in the image?'
msgs = [{'role': 'user', 'content': question}]

res, context, _ = model.chat(
    image=image,
    msgs=msgs,
    context=None,
    tokenizer=tokenizer,
    sampling=True,
    temperature=0.7
)
print(res)
```

# python llama3-minicpm.py
```
/root/miniconda3/envs/llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-07-26 17:00:09,796 - INFO - intel_extension_for_pytorch auto imported
2024-07-26 17:00:09,847 - INFO - vision_config is None, using default vision config
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 17.22it/s]
2024-07-26 17:00:11,545 - INFO - Converting the current model to sym_int4 format......
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/test/kiwi/llama3-minicpm.py", line 24, in <module>
    res, context, _ = model.chat(
                      ^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 416, in chat
    res, vision_hidden_states = self.generate(
                                ^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 326, in generate
    ) = self.get_vllm_embedding(model_inputs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 92, in get_vllm_embedding
    vision_embedding = self.resampler(vision_embedding, tgt_sizes)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/resampler.py", line 150, in forward
    out = self.attn(
          ^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/functional.py", line 5300, in multi_head_attention_forward
    q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/functional.py", line 4846, in _in_projection_packed
    return linear(q, w_q, b_q), linear(k, w_k, b_k), linear(v, w_v, b_v)
                                ^^^^^^^^^^^^^^^^^^^
RuntimeError: could not create a primitive descriptor for a matmul primitive
```

# pip list
```
Package                       Version
----------------------------- ------------------
accelerate                    0.23.0
aiohttp                       3.9.5
aiosignal                     1.3.1
annotated-types               0.7.0
antlr4-python3-runtime        4.9.3
anyio                         4.4.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
async-lru                     2.0.4
attrs                         23.2.0
Babel                         2.15.0
beautifulsoup4                4.12.3
bigdl-core-xe-21              2.5.0b20240725
bigdl-core-xe-addons-21       2.5.0b20240725
bigdl-core-xe-batch-21        2.5.0b20240725
bigdl-core-xe-esimd-21        2.5.0b20240527
bigdl-llm                     2.5.0b20240527
bleach                        6.1.0
certifi                       2024.2.2
cffi                          1.16.0
charset-normalizer            3.3.2
comm                          0.2.2
datasets                      2.20.0
debugpy                       1.8.2
decorator                     5.1.1
defusedxml                    0.7.1
diffusers                     0.29.2
dill                          0.3.8
docstring_parser              0.16
einops                        0.8.0
executing                     2.0.1
fastjsonschema                2.20.0
filelock                      3.14.0
fqdn                          1.5.1
frozenlist                    1.4.1
fsspec                        2024.5.0
h11                           0.14.0
httpcore                      1.0.5
httpx                         0.27.0
huggingface-hub               0.23.2
idna                          3.7
importlib_metadata            8.0.0
intel-extension-for-pytorch   2.1.10+xpu
intel-openmp                  2024.1.2
ipex-llm                      2.1.0b20240725
ipykernel                     6.29.5
ipython                       8.26.0
ipywidgets                    8.1.3
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.4
json5                         0.9.25
jsonpointer                   3.0.0
jsonschema                    4.23.0
jsonschema-specifications     2023.12.1
jupyter                       1.0.0
jupyter_client                8.6.2
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.5
jupyter_server                2.14.2
jupyter_server_terminals      0.5.3
jupyterlab                    4.2.3
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.2
jupyterlab_widgets            3.0.11
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib-inline             0.1.7
mdurl                         0.1.2
mistune                       3.0.2
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
networkx                      3.3
notebook                      7.2.1
notebook_shim                 0.2.4
numpy                         1.26.4
omegaconf                     2.3.0
overrides                     7.7.0
packaging                     24.0
pandas                        2.2.2
pandocfilters                 1.5.1
parso                         0.8.4
pexpect                       4.9.0
pillow                        10.3.0
pip                           24.0
platformdirs                  4.2.2
prometheus_client             0.20.0
prompt_toolkit                3.0.47
protobuf                      5.27.0
psutil                        5.9.8
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       17.0.0
pyarrow-hotfix                0.6
pycparser                     2.22
pydantic                      2.7.1
pydantic_core                 2.18.2
Pygments                      2.18.0
python-dateutil               2.9.0.post0
python-json-logger            2.0.7
pytz                          2024.1
PyYAML                        6.0.1
pyzmq                         26.0.3
qtconsole                     5.5.2
QtPy                          2.4.1
referencing                   0.35.1
regex                         2024.5.15
requests                      2.32.2
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.1
rpds-py                       0.19.0
safetensors                   0.4.3
Send2Trash                    1.8.3
sentencepiece                 0.2.0
setuptools                    69.5.1
shtab                         1.7.1
six                           1.16.0
sniffio                       1.3.1
soupsieve                     2.5
stack-data                    0.6.3
sympy                         1.12.1rc1
tabulate                      0.9.0
terminado                     0.18.1
tiktoken                      0.7.0
timm                          0.9.10
tinycss2                      1.3.0
tokenizers                    0.19.1
torch                         2.1.0a0+cxx11.abi
torchvision                   0.16.0a0+cxx11.abi
tornado                       6.4.1
tqdm                          4.66.4
traitlets                     5.14.3
transformers                  4.40.0
transformers-stream-generator 0.0.5
trl                           0.9.6
types-python-dateutil         2.9.0.20240316
typing_extensions             4.12.0
tyro                          0.8.5
tzdata                        2024.1
uri-template                  1.3.0
urllib3                       2.2.1
wcwidth                       0.2.13
webcolors                     24.6.0
webencodings                  0.5.1
websocket-client              1.8.0
wheel                         0.43.0
widgetsnbextension            4.0.11
xxhash                        3.4.1
yarl                          1.9.4
zipp                          3.19.2
```

**Comment by qiuxin2012** [comment]
We should use transformers==4.41.0. But it's output is not readable.

**Comment by jason-dai** [comment]
> We should use transformers==4.41.0. But it's output is not readable.

Maybe add an example

**Comment by qiuxin2012** [comment]
For the unreadable output, we find it's caused by the `sampling=True`
```python
res, context, _ = model.chat(
    image=image,
    msgs=msgs,
    context=None,
    tokenizer=tokenizer,
    sampling=True,
    temperature=0.7
)
```
If `sampling=True`, the llm's generation will use parameters:
```
                "top_p": 0.8,
                "top_k": 100,
                "temperature": 0.7,
                "do_sample": True,
                "repetition_penalty": 1.05
```
See https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5/blob/main/modeling_minicpmv.py#L328 for details.

The processing of repetition_penalty in [logits_process.py#L346](https://github.com/huggingface/transformers/blob/v4.41.0/src/transformers/generation/logits_process.py#L346) will return a wrong result on XPU. While the result is right on cpu.
So the work around is change the `scores_processed = scores.scatter(1, input_ids, score)` to `scores_processed = scores.to('cpu').scatter(1, input_ids.to('cpu'), score.to('cpu')).to('xpu')`, or set the `sampling=False` like:
```python
res, context, _ = model.chat(
    image=image,
    msgs=msgs,
    context=None,
    tokenizer=tokenizer,
    sampling=False,
    temperature=0
)
```

**Comment by qiuxin2012** [comment]
The wrong result of repetition_penalty is caused by IPEX, I have raised an issue for them https://github.com/intel/intel-extension-for-pytorch/issues/682

**Comment by qiuxin2012** [comment]
Example added https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/HuggingFace/Multimodal/MiniCPM-Llama3-V-2_5
