### ISSUE TITLE
inference qwen1.5-32b-chat failed with DP-AP

### ISSUE THREAD

**Issue by Fred-cell** [intel-analytics/ipex-llm#11669]
install vervion 2.1.0-0b2, and test qwen1.5-32b-chat w/ DP-AP as below:
[1] /home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
[1]   warn(
[2] /home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
[2]   warn(
[3] /home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
[3]   warn(
[0] /home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
[0]   warn(
[3] [2024-07-27 06:18:23,148] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[1] [2024-07-27 06:18:23,148] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[2] [2024-07-27 06:18:23,198] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[0] [2024-07-27 06:18:23,201] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
[0]  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
[0]  [WARNING]  async_io: please install the libaio-dev package with apt
[0]  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[0] [2024-07-27 06:18:23,700] [INFO] [real_accelerator.py:211:set_accelerator] Setting ds_accelerator to cpu (model specified)
[1]  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
[1]  [WARNING]  async_io: please install the libaio-dev package with apt
[1]  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[1] [2024-07-27 06:18:23,700] [INFO] [real_accelerator.py:211:set_accelerator] Setting ds_accelerator to cpu (model specified)
[2]  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
[2]  [WARNING]  async_io: please install the libaio-dev package with apt
[2]  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[2] [2024-07-27 06:18:23,700] [INFO] [real_accelerator.py:211:set_accelerator] Setting ds_accelerator to cpu (model specified)
[3]  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
[3]  [WARNING]  async_io: please install the libaio-dev package with apt
[3]  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[3] [2024-07-27 06:18:23,700] [INFO] [real_accelerator.py:211:set_accelerator] Setting ds_accelerator to cpu (model specified)
Loading checkpoint shards: 100%|██████████| 17/17 [00:48<00:00,  2.84s/it][0]
Loading checkpoint shards: 100%|██████████| 17/17 [00:48<00:00,  2.84s/it]
Loading checkpoint shards: 100%|██████████| 17/17 [00:48<00:00,  2.84s/it]
Loading checkpoint shards: 100%|██████████| 17/17 [00:48<00:00,  2.84s/it]
[1] [2024-07-27 06:19:13,069] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.14.1+ed8aed57, git-hash=ed8aed57, git-branch=HEAD
[2] [2024-07-27 06:19:13,069] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.14.1+ed8aed57, git-hash=ed8aed57, git-branch=HEAD
[3] [2024-07-27 06:19:13,069] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.14.1+ed8aed57, git-hash=ed8aed57, git-branch=HEAD
[0] [2024-07-27 06:19:13,069] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.14.1+ed8aed57, git-hash=ed8aed57, git-branch=HEAD
[3] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no longer needed, please remove from your call to DeepSpeed-inference
[0] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no longer needed, please remove from your call to DeepSpeed-inference
[3] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[1] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no longer needed, please remove from your call to DeepSpeed-inference
[2] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter replace_method is deprecated. This parameter is no longer needed, please remove from your call to DeepSpeed-inference
[0] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[1] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[2] [2024-07-27 06:19:13,070] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter mp_size is deprecated use tensor_parallel.tp_size instead
[3] [2024-07-27 06:19:13,070] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[1] [2024-07-27 06:19:13,070] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[0] [2024-07-27 06:19:13,070] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2] [2024-07-27 06:19:13,070] [INFO] [logging.py:96:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[0] Using /home/intel/.cache/torch_extensions/py311_cpu as PyTorch extensions root...
[2] Using /home/intel/.cache/torch_extensions/py311_cpu as PyTorch extensions root...
[0] Emitting ninja build file /home/intel/.cache/torch_extensions/py311_cpu/deepspeed_ccl_comm/build.ninja...
[0] Building extension module deepspeed_ccl_comm...
[0] Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[0] ninja: no work to do.
[0] Loading extension module deepspeed_ccl_comm...
[2] Loading extension module deepspeed_ccl_comm...
[1] Using /home/intel/.cache/torch_extensions/py311_cpu as PyTorch extensions root...
[1] Emitting ninja build file /home/intel/.cache/torch_extensions/py311_cpu/deepspeed_ccl_comm/build.ninja...
[1] Building extension module deepspeed_ccl_comm...
[1] Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1] ninja: no work to do.
[1] Loading extension module deepspeed_ccl_comm...
[2] Time to load deepspeed_ccl_comm op: 0.10678553581237793 seconds
[2] DeepSpeed deepspeed.ops.comm.deepspeed_ccl_comm_op built successfully
[2] My guessed rank = 2
[2] Traceback (most recent call last):
[2]   File "/home/intel/LLM/ipex-llm/python/llm/example/GPU/Deepspeed-AutoTP/deepspeed_autotp.py", line 76, in <module>
[2]     model = deepspeed.init_inference(
[2]             ^^^^^^^^^^^^^^^^^^^^^^^^^
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/__init__.py", line 341, in init_inference
[2]     engine = InferenceEngine(model, config=ds_inference_config)
[2]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/inference/engine.py", line 123, in __init__
[2]     self._create_model_parallel_group(config)
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/inference/engine.py", line 257, in _create_model_parallel_group
[2]     init_distributed()
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 635, in init_distributed
[2]     init_deepspeed_backend(get_accelerator().communication_backend_name(), timeout, init_method)
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 160, in init_deepspeed_backend
[2]     ccl_backend = CCLBackend(rank=rank, world_size=size, timeout=timeout, init_method=init_method)
[2]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/ccl.py", line 53, in __init__
[2]     super(CCLBackend, self).broadcast(main_kvs, 0)
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
[2]     return fn(*args, **kwargs)
[2]            ^^^^^^^^^^^^^^^^^^^
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/torch.py", line 205, in broadcast
[2]     return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
[2]     return func(*args, **kwargs)
[2]            ^^^^^^^^^^^^^^^^^^^^^
[2]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
[2]     work = default_pg.broadcast([tensor], opts)
[2]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2] RuntimeError: Socket Timeout
[1] Time to load deepspeed_ccl_comm op: 0.08555483818054199 seconds
[1] DeepSpeed deepspeed.ops.comm.deepspeed_ccl_comm_op built successfully
[1] My guessed rank = 1
[1] Traceback (most recent call last):
[1]   File "/home/intel/LLM/ipex-llm/python/llm/example/GPU/Deepspeed-AutoTP/deepspeed_autotp.py", line 76, in <module>
[1]     model = deepspeed.init_inference(
[1]             ^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/__init__.py", line 341, in init_inference
[1]     engine = InferenceEngine(model, config=ds_inference_config)
[1]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/inference/engine.py", line 123, in __init__
[1]     self._create_model_parallel_group(config)
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/inference/engine.py", line 257, in _create_model_parallel_group
[1]     init_distributed()
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 635, in init_distributed
[1]     init_deepspeed_backend(get_accelerator().communication_backend_name(), timeout, init_method)
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/comm.py", line 160, in init_deepspeed_backend
[1]     ccl_backend = CCLBackend(rank=rank, world_size=size, timeout=timeout, init_method=init_method)
[1]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/ccl.py", line 53, in __init__
[1]     super(CCLBackend, self).broadcast(main_kvs, 0)
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
[1]     return fn(*args, **kwargs)
[1]            ^^^^^^^^^^^^^^^^^^^
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/deepspeed/comm/torch.py", line 205, in broadcast
[1]     return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
[1]     return func(*args, **kwargs)
[1]            ^^^^^^^^^^^^^^^^^^^^^
[1]   File "/home/intel/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
[1]     work = default_pg.broadcast([tensor], opts)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1] RuntimeError: Socket Timeout

**Comment by Fred-cell** [comment]
memory exceeds 256GB, and please optimize memory utilization for qwen1.5-32b-chat model.

**Comment by qiuxin2012** [comment]
duplicated with https://github.com/intel-analytics/ipex-llm/issues/11635
