### ISSUE TITLE
glm4:AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by jjzhu0579** [intel-analytics/ipex-llm#11714]
python3.11
transformers4.42.4

**Comment by jjzhu0579** [comment]
Traceback (most recent call last):
  File "/share/home/aim/aim_zhujj/bc2/glm4_lora_train.py", line 138, in <module>
    trainer.train()
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/transformers/trainer.py", line 3318, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/transformers/trainer.py", line 3363, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/peft/peft_model.py", line 1625, in forward
    return self.base_model(inputs_embeds=inputs_embeds, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/aim/aim_zhujj/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 878, in forward
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/aim_nuist/aim_zhujj/.conda/envs/blurb/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/home/aim/aim_zhujj/.cache/huggingface/modules/transformers_modules/glm-4-9b-chat/modeling_chatglm.py", line 757, in forward
    batch_size, seq_length = input_ids.shape
                             ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Uxito-Ada** [comment]
Hi @jjzhu0579 ,

We do not support transformers 4.42.4.

It seems that there is a chatglm-fine-tuneing application wrote by yourself, named `glm4_lora_train.py`, while we have provided LoRA fine-tuning for ChatGLM on IPEX-LLM. Pls follow [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/LLM-Finetuning/LoRA/chatglm_finetune#lora-fine-tuning-on-chatglm3-6b-with-ipex-llm) to try it.

**Comment by jjzhu0579** [comment]
> Hi @jjzhu0579 ,
> 
> It seems that there is a ChatGLM-fine-tuneing application wrote by yourself, named `glm4_lora_train.py`, while we have provided LoRA fine-tuning for ChatGLM on IPEX-LLM. Pls follow [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/LLM-Finetuning/LoRA/chatglm_finetune#lora-fine-tuning-on-chatglm3-6b-with-ipex-llm) to try it. And currently, we do not support transformers 4.42.4 in ChatGLM fine-tuning.

sorry ，the name is wrong,it is the p-tuning

**Comment by jjzhu0579** [comment]
![image](https://github.com/user-attachments/assets/aa409c4e-4f08-41eb-b72d-929512821aba)

**Comment by Uxito-Ada** [comment]
Hi @jjzhu0579 ,

Sorry that p-tuning has not been supported. You can find all available fine-tuning algorithms [here](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/LLM-Finetuning#running-llm-finetuning-using-ipex-llm-on-intel-gpu). In addition, IPEX-LLM works only on Intel XPU rather than CUDA.
