### ISSUE TITLE
Could you help to optimize MiniCPM-V-2_6?

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#11731]
Hi, I run MiniCPM-V-2_6 on MTL iGPU. But it is a little slow and needs to optimize.
Could you help to optimize MiniCPM-V-2_6?
Thanks.

When using FP16 to caculate, get the following error:
```
Traceback (most recent call last):
  File "C:\Users\test\Documents\LLM\cpm.py", line 332, in <module>
    res = model.chat(
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6\modeling_minicpmv.py", line 378, in chat
    res = self.generate(
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6\modeling_minicpmv.py", line 262, in generate
    result = self._decode(model_inputs["inputs_embeds"], tokenizer, attention_mask, decode_text=decode_text, **kwargs)
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6\modeling_minicpmv.py", line 186, in _decode
    output = self.llm.generate(
  File "C:\Users\test\miniforge3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\ipex_llm\transformers\lookup.py", line 88, in generate
    return original_generate(self,
  File "C:\Users\test\miniforge3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\ipex_llm\transformers\speculative.py", line 109, in generate
    return original_generate(self,
  File "C:\Users\test\miniforge3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\ipex_llm\transformers\pipeline_parallel.py", line 280, in generate
    return original_generate(self,
  File "C:\Users\test\miniforge3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\transformers\generation\utils.py", line 1592, in generate
    return self.sample(
  File "C:\Users\test\miniforge3\lib\site-packages\transformers\generation\utils.py", line 2734, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
We can use FP16 to caculate for this model, right?

**Comment by MeouSker77** [comment]
solved in latest nightly released ipex_llm

**Comment by violet17** [comment]
Thank you very much!
