### ISSUE TITLE
MiniCPM-V-2.6 load_low_bit fails

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#11762]
error log:
```
2024-08-12 12:01:43,432 - INFO - vision_config is None, using default vision config
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "C:\Users\test\Documents\LLM\cpm.py", line 339, in <module>
    res = model.chat(
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_minicpmv.py", line 302, in chat
    assert self.config.query_num == processor.image_processor.image_feature_size, "These two values should be the same. Check `config.json` and `preprocessor_config.json`."
AttributeError: 'MiniCPMVTokenizerFast' object has no attribute 'image_processor'
```

Can you help to fix this issue? Thanks.

Version:
ipex-llm 2.1.0b20240811

**Comment by leonardozcm** [comment]
> AttributeError: 'MiniCPMVTokenizerFast' object has no attribute 'image_processor'

I believe this is because of you pass a tokenizer instance to where the arg expects a  `MiniCPMVImageProcessor `instance in `chat`.
You also need to call `save_pretrained `to both dump `MiniCPMVImageProcessor ` instance and `MiniCPMVTokenizerFast` instance to your int4 model directory too. That is:
```
from ipex_llm.transformers import AutoModel
from transformers import AutoTokenizer, AutoProcessor

model_path = "/path/to/MiniCPM-V-2_6"

# replace the args that you need
    model = AutoModel.from_pretrained(model_path, 
                                      load_in_4bit=True,
                                      optimize_model=False,
                                      trust_remote_code=True,
                                      modules_to_not_convert=["vpm", "resampler"],
                                      use_cache=True)
    processor = AutoProcessor.from_pretrained(model_path,
                                              load_in_4bit=True,
                                              optimize_model=False,
                                              trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained(model_path,
                                              trust_remote_code=True)

model_path_int4 = model_path+"-int4"

# save model, processor and tokenizer before you run load_low_bit
model.save_low_bit(model_path_int4 )
processor.save_pretrained(model_path_int4 )
tokenizer.save_pretrained(model_path_int4 )
```
My transformers version == 4.40

**Comment by violet17** [comment]
Thanks.
And how to load all modules in INT4 instead of using `modules_to_not_convert=["vpm", "resampler"],`?

**Comment by leonardozcm** [comment]
> Thanks. And how to load all modules in INT4 instead of using `modules_to_not_convert=["vpm", "resampler"],`?

synced offline, now load_low_bit is working on all modules of minicpm-v

**Comment by leonardozcm** [comment]
Following issues transfer to https://github.com/intel-analytics/ipex-llm/issues/11797
