### ISSUE TITLE
MiniCPM-V-2_6 load_low_bit mode.chat fails on MTL iGPU

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#11797]
MiniCPM-V-2_6 load_low_bit mode.chat fails on MTL iGPU windows
log：
```
python test_cpm.py
C:\Users\test\miniforge3\lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
C:\Users\test\miniforge3\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\test\miniforge3\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-08-14 16:14:47,978 - INFO - intel_extension_for_pytorch auto imported
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-08-14 16:14:48,316 - INFO - vision_config is None, using default vision config
2024-08-14 16:14:49,763 - INFO - Converting the current model to sym_int4 format......
C:\Users\test\miniforge3\lib\site-packages\torch\nn\init.py:412: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
model.config.model_type == minicpmv
model.vpm.config.model_type  siglip_vision_model
Loading checkpoint shards:   0%|                                                                 | 0/2 [00:00<?, ?it/s]C:\Users\test\miniforge3\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.15s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "C:\Users\test\Documents\LLM\test_cpm.py", line 51, in <module>
    res = model.chat(
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_minicpmv.py", line 378, in chat
    res = self.generate(
  File "C:\Users\test\miniforge3\lib\site-packages\ipex_llm\transformers\models\minicpmv.py", line 76, in generate
    return origin_generate(
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_minicpmv.py", line 257, in generate
    ) = self.get_vllm_embedding(model_inputs)
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_minicpmv.py", line 107, in get_vllm_embedding
    vision_embedding = self.vpm(all_pixel_values.type(dtype), patch_attention_mask=patch_attn_mask, tgt_sizes=tgt_sizes).last_hidden_state
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_navit_siglip.py", line 918, in forward
    encoder_outputs = self.encoder(
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_navit_siglip.py", line 826, in forward
    layer_outputs = encoder_layer(
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_navit_siglip.py", line 670, in forward
    hidden_states, attn_weights = self.self_attn(
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\.cache\huggingface\modules\transformers_modules\MiniCPM-V-2_6-int4\modeling_navit_siglip.py", line 390, in forward
    query_states = self.q_proj(hidden_states)
  File "C:\Users\test\miniforge3\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SiglipAttention' object has no attribute 'q_proj'. Did you mean: 'qkv_proj'?
```
code：
```
import time
import torch
from PIL import Image
from transformers import AutoModel, AutoTokenizer, AutoProcessor
from ipex_llm.transformers import AutoModel

model_path = r"models/MiniCPM-V-2_6"
model_path = r"models/MiniCPM-V-2_6-int4"

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

if 0:

    model = AutoModel.from_pretrained(model_path, trust_remote_code=True,optimize_model=True,
                                    load_in_low_bit="sym_int4").eval()
    

    processor = AutoProcessor.from_pretrained(model_path,
                                                load_in_4bit=True,
                                                optimize_model=True,
                                                trust_remote_code=True)

    model_path_int4 = model_path+"-int4"

    # save model, processor and tokenizer before you run load_low_bit
    print("save model----------")
    model.save_low_bit(model_path_int4 )
    processor.save_pretrained(model_path_int4 )
    tokenizer.save_pretrained(model_path_int4 )
else:
    model = AutoModel.load_low_bit(model_path,trust_remote_code=True, optimize_model=True).eval()


model = model.half()


model = model.to('xpu')

# print(model)

image = Image.open('test_image/guo.png').convert('RGB')
question = 'What is in the image?'
question = '描述这幅图'
msgs = [{'role': 'user', 'content': [image, question]}]


with torch.inference_mode():
    for i in range(1):
        st = time.time()
        res = model.chat(
            image=None,
            msgs=msgs,
            tokenizer=tokenizer,
            max_new_tokens=127,
        )
        et = time.time()
        print(res)
        print(et - st)
```

version:
```
transformers                4.40.0
ipex-llm                    2.1.0b20240813
bigdl-core-xe-21            2.5.0b20240813
bigdl-core-xe-addons-21     2.5.0b20240813
bigdl-core-xe-batch-21      2.5.0b20240813
```

**Comment by leonardozcm** [comment]
fixed in https://github.com/intel-analytics/ipex-llm/issues/11762
