### ISSUE TITLE
Models failed while running harness test (winogrande dataset) with latest IPEX-LLM nightly build

### ISSUE THREAD

**Issue by yzha107** [intel-analytics/ipex-llm#12004]
A lot of models failed while running harness test (winogrande dataset) with IPEX-LLM nightly build after 2.1.0b20240820

For example:
Model: codegemma-7b-it
IPEX-LLM version: 2.2.0b20240902
transformers version: 4.38.2

Environment:
```
Hardware: ThinkBook14G6+IMH-Ultra7-155H-32GB
OS: Windows 11
```

Steps to reproduce:

1. Covert the model to 'sym_int4' by `<ipex-llm-repo-root>/python/llm/dev/benchmark/all-in-one/save.py`
2. Install harness packages by following the instruction of [link](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/dev/benchmark/harness#install-harness)
3. Go to directory `<ipex-llm-repo-root>/python/llm/dev/benchmark/harness`
4. Run command `python run_llb.py --model ipex-llm --pretrained <model_hub_path>\codegemma-7b-it-int4 --precision sym_int4 --device xpu --tasks winogrande --no_cache --batch 1`

Error log:
```
Running IPEX-LLM harness test ...
Could not import signal.SIGPIPE (this is expected on Windows machines)
C:\Users\superbuilder\miniforge3\envs\ipex-llm-acc\Lib\site-packages\transformers\deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
C:\Users\superbuilder\miniforge3\envs\ipex-llm-acc\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\superbuilder\miniforge3\envs\ipex-llm-acc\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-09-04 15:21:12,329 - INFO - intel_extension_for_pytorch auto imported
Selected Tasks: ['winogrande']
2024-09-04 15:21:13,484 - INFO - Converting the current model to sym_int4 format......
Loading checkpoint shards:   0%|                                                                                                     | 0/2 [00:00<?, ?it/s]C:\Users\superbuilder\miniforge3\envs\ipex-llm-acc\Lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.31s/it]
Task: winogrande; number of docs: 1267
Task: winogrande; document 0; context prompt (starting on next line):
Natalie took basic French lessons from Betty after school because Betty is strong at that language.

My friends tried to drive the car through the alleyway but the car was too wide.

Sarah didn't practice ballet much but Mary practiced all the time. Sarah wasn't chosen to be a lead dancer.

The trainer tried to put the exercise equipment in the van but it wouldn't fit; the van was too small.

Natalie never checks the air in the tires while Tanya does and you just knew Natalie would have flat tires.

People think Rebecca
(end of prompt on previous line)
Requests: [Req_loglikelihood("Natalie took basic French lessons from Betty after school because Betty is strong at that language.\n\nMy friends tried to drive the car through the alleyway but the car was too wide.\n\nSarah didn't practice ballet much but Mary practiced all the time. Sarah wasn't chosen to be a lead dancer.\n\nThe trainer tried to put the exercise equipment in the van but it wouldn't fit; the van was too small.\n\nNatalie never checks the air in the tires while Tanya does and you just knew Natalie would have flat tires.\n\nPeople think Samantha", ' is embarassed, because Samantha made snide comments about the shirt Rebecca was wearing.')[0]
, Req_loglikelihood("Natalie took basic French lessons from Betty after school because Betty is strong at that language.\n\nMy friends tried to drive the car through the alleyway but the car was too wide.\n\nSarah didn't practice ballet much but Mary practiced all the time. Sarah wasn't chosen to be a lead dancer.\n\nThe trainer tried to put the exercise equipment in the van but it wouldn't fit; the van was too small.\n\nNatalie never checks the air in the tires while Tanya does and you just knew Natalie would have flat tires.\n\nPeople think Rebecca", ' is embarassed, because Samantha made snide comments about the shirt Rebecca was wearing.')[0]
]
Running loglikelihood requests
  0%|                                                                                                                             | 0/2534 [00:02<?, ?it/s]
Job config of task=winogrande, precision=sym_int4 failed. Error Message: The size of tensor a (0) must match the size of tensor b (10) at non-singleton dimension 1
Here are results of all successful tasks:
Traceback (most recent call last):
  File "C:\WorkSpace\superbuilder\llm.model.benchmark\ipex_llm_harness\run_llb.py", line 159, in <module>
    main()
  File "C:\WorkSpace\superbuilder\llm.model.benchmark\ipex_llm_harness\run_llb.py", line 155, in main
    raise RuntimeError('\n'.join(fail))
RuntimeError: Job config of task=winogrande, precision=sym_int4 failed. Error Message: The size of tensor a (0) must match the size of tensor b (10) at non-singleton dimension 1
```

**Comment by cranechu0131** [comment]
We encountered some problems when reproducing the issue and have made a contact with the user. Still in progress.

**Comment by cranechu0131** [comment]
Hi yzha107，
 We have looked into the issue and reproduced the problem. The current conclusion is that ipex-llm after 2.1.0b20240820 introduced this change [set IPEX_LLM_LAST_LM_HEAD=1 as default](https://github.com/intel-analytics/ipex-llm/commit/0236de3ac2042b79941744d18ed4107ab70cbf09)   which demands running the following command before the harness evaluation,

for linux users:
```
export IPEX_LLM_LAST_LM_HEAD=0
```

for windows users:
```
$env:IPEX_LLM_LAST_LM_HEAD=0
```

Doing so should solve the problem.

**Comment by lalalapotter** [comment]
Issue is already solved for user, close issue.
