### ISSUE TITLE
Running Qwen2-7B gets error on LNL NPU after appeding history

### ISSUE THREAD

**Issue by violet17** [intel-analytics/ipex-llm#12025]
prompt:
```
 <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
hi<|im_end|>
<|im_start|>system
Hello! How can I assist you today?<|im_end|>
<|im_start|>user
北京三日游<|im_end|>
<|im_start|>system
您好！关于北京三日游的回答如下：

第一天：
您可以参观故宫博物院，这是中国最大的古代宫殿建筑群和世界四大博物馆之一；
午餐时，别忘了品尝正宗的北京烤鸭；
下午游览天安门广场和人民英雄纪念碑；
晚上，您可以去王府井大街逛街购物，并享受各种美食小吃。

第二天：
参观长城是您不能错过的行程的一部分；
早餐后出发前往八达岭长城；
午餐时，推荐品尝炸酱面或豆汁等北京特色美食；
下午游览颐和园，这是一个集皇家园林、江南水乡风光于一体的大型园林景区；
晚上，您可以去前门大街感受老北京的传统商业街氛围。

第三天：
参观国家博物馆，了解中国的历史和文化；
上午逛南锣鼓巷，体验老北京的生活风情；
午餐时，推荐品尝豆汁、炒肝等北京传统早点；
下午游览景山公园，登上万寿山俯瞰整个城市的美景；
晚上，您可以去798艺术区欣赏现代艺术作品和个人展览。

祝您在北京三日游中玩得愉快！<|im_end|>
<|im_start|>user
根据用户提问回答问题。回答的语种与问题的语种一致。

问: 北京三日游
<|im_end|>
<|im_start|>assistant
```

log:
```
start compiling
loc(fused<{name = "Add_1106", type = "Add"}>["Add_1106", "_mem_permute_1"]): error: PermuteCast input and output distributions are incompatible: in = #VPU.DistributedTensor<mode = <SEGMENTED>, num_tiles = [1, 4, 1, 1], num_clusters = 4 : i64, uniform_distributed_segments = unit, compute_shapes = [[1, 7, 304, 128], [1, 7, 304, 128], [1, 7, 304, 128], [1, 7, 304, 128]], compute_offsets = [[0, 0, 0, 0], [0, 7, 0, 0], [0, 14, 0, 0], [0, 21, 0, 0]], memory_shapes = [[1, 7, 304, 128], [1, 7, 304, 128], [1, 7, 304, 128], [1, 7, 304, 128]], memory_offsets = [[0, 0, 0, 0], [0, 7, 0, 0], [0, 14, 0, 0], [0, 21, 0, 0]]>, out = #VPU.DistributedTensor<mode = <OVERLAPPED>, num_tiles = [1, 1, 4, 1], num_clusters = 4 : i64, uniform_distributed_segments = unit, compute_shapes = [[1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304]], compute_offsets = [[0, 0, 0, 0], [0, 0, 7, 0], [0, 0, 14, 0], [0, 0, 21, 0]], memory_shapes = [[1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304]], memory_offsets = [[0, 0, 0, 0], [0, 0, 7, 0], [0, 0, 14, 0], [0, 0, 21, 0]]>,expected = #VPU.DistributedTensor<mode = <SEGMENTED>, num_tiles = [1, 1, 4, 1], num_clusters = 4 : i64, uniform_distributed_segments = unit, compute_shapes = [[1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304]], compute_offsets = [[0, 0, 0, 0], [0, 0, 7, 0], [0, 0, 14, 0], [0, 0, 21, 0]], memory_shapes = [[1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304], [1, 128, 7, 304]], memory_offsets = [[0, 0, 0, 0], [0, 0, 7, 0], [0, 0, 14, 0], [0, 0, 21, 0]]>
Process Process-5:
Traceback (most recent call last):
  File "C:\work\AIGC_npu\resources\env\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\work\AIGC_npu\resources\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\ipex_llm\transformers\npu_models\qwen2_mp.py", line 875, in run_prefill
    layer_outputs = decoder_layer(
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\ipex_llm\transformers\npu_models\qwen2_mp.py", line 514, in forward
    hidden_states, past_key, past_value = run_model(
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\ipex_llm\transformers\npu_models\mp_models_base.py", line 75, in run_model
    _model_cache[key] = deque([backend_cls(*input_shapes) for i in range(replica)])
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\ipex_llm\transformers\npu_models\mp_models_base.py", line 75, in <listcomp>
    _model_cache[key] = deque([backend_cls(*input_shapes) for i in range(replica)])
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\ipex_llm\transformers\npu_models\qwen2_mp.py", line 225, in __init__
    self.compile()
  File "C:\work\AIGC_npu\resources\env\lib\site-packages\intel_npu_acceleration_library\backend\factory.py", line 837, in compile
    backend_lib.compile(self._mm)
OSError: [WinError -529697949] Windows Error 0xe06d7363
```

Version:
ipex-llm                      2.2.0b20240903 or 0904
bigdl-core-npu                2.6.0b20240903 or 0904

**Comment by plusbang** [comment]
Hi, @violet17 , as we communicated offline, the compile error is caused by the specific input length 336. In https://github.com/intel-analytics/ipex-llm/pull/12033, we would pad input to `max_prompt_len` and this error could be solved.

Please wait for nightly version including this fix and have a try.

**Comment by violet17** [comment]
Fixed. Thanks.
