### ISSUE TITLE
undefined symbol: iJIT_NotifyEvent  with oneapi 2024.2, but no issue with 2024.0.1

### ISSUE THREAD

**Issue by Jianshui** [intel-analytics/ipex-llm#12112]
I tried ipex-llm with ARC770, but meet undefined symbol: iJIT_NotifyEvent  with oneapi 2024.2, no issue with oneapi 2024.0.1

python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gta/conda/envs/llm/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/gta/conda/envs/llm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

**Comment by liu-shaojun** [comment]
Hi @Jianshui Based on our offline sync, we currently recommend using oneAPI 2024.0.1 If we upgrade to 2024.2 in the future, we will update you accordingly.

**Comment by Jianshui** [comment]
thanks @liu-shaojun 
I saw there is also new ipex release, normally it's validated with latest oneapi toolkit 
[v2.3.110+xpu](https://github.com/intel/intel-extension-for-pytorch/releases/tag/v2.3.110%2Bxpu)

**Comment by kunger97** [comment]
> Hi @Jianshui Based on our offline sync, we currently recommend using oneAPI 2024.0.1 If we upgrade to 2024.2 in the future, we will update you accordingly.

Intel® oneAPI Base Toolkit now update to 2024.2 and can not download older version if i don't have Priority Support witch is paid.
