### ISSUE TITLE
Undefined symbol on ipex 2.3.110+xpu

### ISSUE THREAD

**Issue by notsyncing** [intel-analytics/ipex-llm#12143]
Hello, I'm trying ipex-llm 2.2.0b20240927 with pytorch ipex 2.3.110+xpu, and it failed with following error:

```
ERROR    azarrot.backends.common:common.py:323 An error occurred when generating text
Traceback (most recent call last):
  File "/mnt/data/podman/Projects/azarrot/src/azarrot/backends/common.py", line 319, in generate
    self.model.generate(**self.generation_kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/ipex_llm/transformers/lookup.py", line 123, in generate
    return original_generate(self,
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/ipex_llm/transformers/speculative.py", line 109, in generate
    return original_generate(self,
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/ipex_llm/transformers/pipeline_parallel.py", line 283, in generate
    return original_generate(self,
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 146, in wrapped
    return module_call(self, *args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/ipex_llm/transformers/models/qwen2.py", line 437, in qwen2_causal_lm_forward
    outputs = self.model(
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 146, in wrapped
    return module_call(self, *args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/ipex_llm/transformers/models/qwen2.py", line 371, in qwen2_model_forward_4_42
    layer_outputs = decoder_layer(
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 146, in wrapped
    return module_call(self, *args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 652, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 146, in wrapped
    return module_call(self, *args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/ipex_llm/transformers/models/llama.py", line 257, in llama_rms_norm_forward
    import xe_addons
ImportError: /mnt/data/podman/Projects/azarrot/venv/lib/python3.10/site-packages/xe_addons.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops8to_dtype4callERKNS_6TensorEN3c1010ScalarTypeEbbNS5_8optionalINS5_12MemoryFormatEEE
```

This does not happen on ipex 2.1.40+xpu. 

Do you have any plan on adding support for ipex 2.3.110+xpu? Thanks!

**Comment by Oscilloscope98** [comment]
Hi @notsyncing, `ipex-llm` currently supports PyTorch 2.1 :)
