### ISSUE TITLE
Traceback (most recent call last):   File "/home/wxf/ipex-llm/minicpm/xin-minicpm-v2-6.py", line 2, in <module>     import torch   File "/home/wxf/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>     from torch._C import *  # noqa: F403     ^^^^^^^^^^^^^^^^^^^^^^ ImportError: /home/wxf/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

### ISSUE THREAD

**Issue by yangqing-yq** [intel-analytics/ipex-llm#12141]
Traceback (most recent call last):
  File "/home/wxf/ipex-llm/minicpm/xin-minicpm-v2-6.py", line 2, in <module>
    import torch
  File "/home/wxf/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/wxf/miniforge3/envs/ipex-llm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

**Comment by qiuxin2012** [comment]
It looks like you are using oneapi 2024.2, oneapi 2024.2 is not supported now, the same error is in https://github.com/intel-analytics/ipex-llm/issues/12112.
You need to remove your oneapi and install oneapi 2024.0 like this https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/install_linux_gpu.md#install-oneapi.
