### ISSUE TITLE
docker container cannot run Qwen2.5 32b awq int4 quantization model （OOM）

### ISSUE THREAD

**Issue by sarsmlee** [intel-analytics/ipex-llm#12228]
docker container version ： ipex-llm-serving-xpu:2.2.0-b2

start shell script：

model="/llm/models/Qwen/Qwen2.5-32B-Instruct-AWQ"
served_model_name="Qwen2.5-32B-Instruct-AWQ"

export CCL_WORKER_COUNT=4
export FI_PROVIDER=shm
export CCL_ATL_TRANSPORT=ofi
export CCL_ZE_IPC_EXCHANGE=sockets
export CCL_ATL_SHM=1

export USE_XETLA=OFF
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=2
export TORCH_LLM_ALLREDUCE=0

source /opt/intel/1ccl-wks/setvars.sh

python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server \
  --served-model-name $served_model_name \
  --port 8000 \
  --model $model \
  --trust-remote-code \
  --block-size 8 \
  --gpu-memory-utilization 0.95 \
  --device xpu \
  --dtype float16 \
  --enforce-eager \
  --quantization=awq \
  --load-in-low-bit asym_int4 \
  --max-model-len 4096 \
  --max-num-batched-tokens 4096 \
  --max-num-seqs 12 \
  --tensor-parallel-size 4     

error log：

/usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-10-18 10:01:26,205 - INFO - intel_extension_for_pytorch auto imported
2024-10-18 10:01:28,551 - INFO - PyTorch version 2.1.0.post2+cxx11.abi available.
INFO 10-18 10:01:28 api_server.py:341] vLLM API server version 0.5.4
INFO 10-18 10:01:28 api_server.py:342] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, load_in_low_bit='asym_int4', model='/llm/models/Qwen/Qwen2.5-32B-Instruct-AWQ', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='float16', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=4096, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=8, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.95, num_gpu_blocks_override=None, max_num_batched_tokens=4096, max_num_seqs=12, max_logprobs=20, disable_log_stats=False, quantization='awq', rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='xpu', scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['Qwen2.5-32B-Instruct-AWQ'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 10-18 10:01:28 awq_marlin.py:89] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 10-18 10:01:29 awq_marlin.py:93] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference
WARNING 10-18 10:01:29 config.py:254] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 10-18 10:01:29 config.py:729] Defaulting to use ray for distributed inference
2024-10-18 10:01:31,133	INFO worker.py:1786 -- Started a local Ray instance.
INFO 10-18 10:01:31 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='/llm/models/Qwen/Qwen2.5-32B-Instruct-AWQ', speculative_config=None, tokenizer='/llm/models/Qwen/Qwen2.5-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=xpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=Qwen2.5-32B-Instruct-AWQ, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 10-18 10:01:32 ray_gpu_executor.py:113] use_ray_spmd_worker: False
INFO 10-18 10:01:32 ray_gpu_executor.py:116] driver_ip: 192.168.90.161
(pid=19092) /usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
(pid=19092)   warn(
(pid=19092) 2024-10-18 10:01:34,867 - INFO - intel_extension_for_pytorch auto imported
(pid=19092) 2024-10-18 10:01:36,958 - INFO - PyTorch version 2.1.0.post2+cxx11.abi available.
(pid=19086) /usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
(pid=19086)   warn(
(pid=19086) 2024-10-18 10:01:40,400 - INFO - intel_extension_for_pytorch auto imported
(pid=19086) 2024-10-18 10:01:42,235 - INFO - PyTorch version 2.1.0.post2+cxx11.abi available.
(pid=19070) /usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
(pid=19070)   warn(
(pid=19070) 2024-10-18 10:01:46,137 - INFO - intel_extension_for_pytorch auto imported
(pid=19070) 2024-10-18 10:01:47,986 - INFO - PyTorch version 2.1.0.post2+cxx11.abi available.
(pid=19090) /usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
(pid=19090)   warn(
(pid=19090) 2024-10-18 10:01:51,595 - INFO - intel_extension_for_pytorch auto imported
(pid=19090) 2024-10-18 10:01:53,683 - INFO - PyTorch version 2.1.0.post2+cxx11.abi available.
(WrapperWithLoadBit pid=19090) INFO 10-18 10:01:54 selector.py:127] Cannot use _Backend.FLASH_ATTN backend on XPU.
(WrapperWithLoadBit pid=19090) INFO 10-18 10:01:54 selector.py:76] Using IPEX attention backend.
INFO 10-18 10:01:54 selector.py:127] Cannot use _Backend.FLASH_ATTN backend on XPU.
INFO 10-18 10:01:54 selector.py:76] Using IPEX attention backend.
INFO 10-18 10:01:55 shm_broadcast.py:235] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x7a949f051c50>, local_subscribe_port=34455, remote_subscribe_port=None)
INFO 10-18 10:01:55 selector.py:127] Cannot use _Backend.FLASH_ATTN backend on XPU.
INFO 10-18 10:01:55 selector.py:76] Using IPEX attention backend.
Loading safetensors checkpoint shards:   0% Completed | 0/5 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  20% Completed | 1/5 [00:00<00:00,  9.47it/s]
Loading safetensors checkpoint shards:  60% Completed | 3/5 [00:00<00:00,  9.61it/s]
Loading safetensors checkpoint shards:  80% Completed | 4/5 [00:00<00:00,  9.45it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:00<00:00,  8.58it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:00<00:00,  8.92it/s]

2024-10-18 10:01:56,284 - INFO - Converting the current model to asym_int4 format......
2024-10-18 10:01:56,285 - INFO - Only HuggingFace Transformers models are currently supported for further optimizations
2024-10-18 10:02:04,861 - INFO - Only HuggingFace Transformers models are currently supported for further optimizations
2024-10-18 10:02:07,068 - INFO - Loading model weights took 4.5634 GB
(raylet) [2024-10-18 10:02:31,128 E 18935 18935] (raylet) node_manager.cc:3065: 2 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: b9d5403570e4f1abb46f2737a2c1be4c32058847ebfbb4f52dcbc1ec, IP: 192.168.90.161) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 192.168.90.161`
(raylet) 
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
(WrapperWithLoadBit pid=19086) 2024-10-18 10:02:44,277 - INFO - Loading model weights took 4.5634 GB
Process Process-65:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/entrypoints/openai/rpc/server.py", line 220, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, port, load_in_low_bit)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/entrypoints/openai/rpc/server.py", line 27, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(async_engine_args,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/engine/engine.py", line 43, in from_engine_args
    return super().from_engine_args(engine_args, start_engine_loop, usage_context, stat_loggers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 476, in from_engine_args
    engine = cls(
             ^^^^
  File "/usr/local/lib/python3.11/dist-packages/ipex_llm/vllm/xpu/engine/engine.py", line 29, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 381, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 557, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/engine/llm_engine.py", line 255, in __init__
    self.model_executor = executor_class(
                          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/ray_xpu_executor.py", line 35, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/ray_gpu_executor.py", line 555, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/distributed_gpu_executor.py", line 25, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/xpu_executor.py", line 53, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/ray_gpu_executor.py", line 61, in _init_executor
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/ray_gpu_executor.py", line 231, in _init_workers_ray
    self._run_workers("load_model",
  File "/usr/local/lib/python3.11/dist-packages/vllm-0.5.4+xpu-py3.11-linux-x86_64.egg/vllm/executor/ray_gpu_executor.py", line 481, in _run_workers
    ray_worker_outputs = ray.get(ray_worker_outputs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py", line 2691, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ray/_private/worker.py", line 873, in get_objects
    raise value
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 192.168.90.161, ID: b9d5403570e4f1abb46f2737a2c1be4c32058847ebfbb4f52dcbc1ec) where the task (actor ID: 5cbcdf01173a96b6cbe984de01000000, name=WrapperWithLoadBit.__init__, pid=19090, memory used=5.55GB) was running was 32.00GB / 32.00GB (0.999909), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 91d5f409dd64d573ab42451e1e6e45ae8344bfc45cf2637f1a6dc562) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 192.168.90.161`. To see the logs of the worker, use `ray logs worker-91d5f409dd64d573ab42451e1e6e45ae8344bfc45cf2637f1a6dc562*out -ip 192.168.90.161. Top 10 memory users:
PID	MEM(GB)	COMMAND
18782	9.89	python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server --served-model-name Qwen2.5-32B-Instruct-A...
19086	5.74	ray::WrapperWithLoadBit.execute_method
19090	5.55	ray::WrapperWithLoadBit.execute_method
19070	5.46	ray::WrapperWithLoadBit.execute_method
19092	0.21	ray::WrapperWithLoadBit
18602	0.17	python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server --served-model-name Qwen2.5-32B-Instruct-A...
18785	0.17	/usr/local/lib/python3.11/dist-packages/ray/core/src/ray/gcs/gcs_server --log_dir=/tmp/ray/session_2...
18877	0.07	/usr/bin/python /usr/local/lib/python3.11/dist-packages/ray/dashboard/dashboard.py --host=127.0.0.1 ...
19037	0.05	/usr/bin/python -u /usr/local/lib/python3.11/dist-packages/ray/dashboard/agent.py --node-ip-address=...
18935	0.05	/usr/local/lib/python3.11/dist-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray...
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
/usr/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by sarsmlee** [comment]
found a solution. need to adjust the size of the container startup memory and shared memory.
After modification, it can be started normally

docker run -itd         
--Net=host
--Device=/dev/dri
-V/path/:/path
-E no_proxy=localhost, 127.0.0.1
--Memory="64G"
--Name=arc_test
--Shm size="32g"
$DOCKER_IMAGE
