### ISSUE TITLE
IPEX-LLM load qwen2.5 7B model failed

### ISSUE THREAD

**Issue by HoppeDeng** [intel-analytics/ipex-llm#12273]
ipex-llm xpu version failed to load qwen2.5 7b instruct model on win11.

ipex-llm version : 2.2.0b20241024
transformers version: 4.37.0

The error log is below:
 
2024-10-25 23:03:36,101 - INFO - Converting the current model to sym_int4 format......
C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\nn\init.py:452: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Traceback (most recent call last):
  File "C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back\start.py", line 578, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back\start.py", line 58, in create_app
    bot = LLMGLM()
          ^^^^^^^^
  File "C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back\models\chatllm.py", line 27, in __init__
    self.llm = init_model()
               ^^^^^^^^^^^^
  File "C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back\models\chatllm.py", line 18, in init_model
    llm = TransformersLLM.from_model_id(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HB\qwen_ultrachat\ultrachat\trunk\back\models\bigdl_llm.py", line 83, in from_model_id
    model.to(LLM_DEVICE)
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\transformers\modeling_utils.py", line 2597, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\nn\modules\module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\nn\modules\module.py", line 779, in _apply
    module._apply(fn)
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\nn\modules\module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\nn\modules\module.py", line 1159, in convert
    return t.to(
           ^^^^^
  File "C:\Users\HB\miniforge3\envs\uc_back\Lib\site-packages\torch\xpu\__init__.py", line 117, in _lazy_init
    torch._C._xpu_init()
RuntimeError: Native API failed. Native API returns: -30 (PI_ERROR_INVALID_VALUE) -30 (PI_ERROR_INVALID_VALUE)

Is there a way to fix it?

**Comment by HoppeDeng** [comment]
Conflict with openvino 2024.0
