### ISSUE TITLE
llava-hf/llava-1.5-7b-hf: error when multi-turn chat with multi-images

### ISSUE THREAD

**Issue by Johere** [intel-analytics/ipex-llm#12288]
Multi-turn chat is like:
- 1st-round: 
http://farm6.staticflickr.com/5268/5602445367_3504763978_z.jpg
What is this?

- 2nd-round:
http://farm5.staticflickr.com/4031/4440753665_631134eaa4_z.jpg
What are the differences between these two images?

Error logs:
```
Traceback (most recent call last): 
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner 
    self.run() 
  File "/usr/lib/python3.10/threading.py", line 953, in run 
    self._target(*self._args, **self._kwargs) 
  File "/home/ipex-llm-serving/dependency/model_worker.py", line 85, in model_generate 
    raise NotImplementedError(f"Unsupported model: {self.model_name}, error: {error}") 
NotImplementedError: Unsupported model: llava-hf/llava-1.5-7b-hf, error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead. 
```

The error is located as:
/home/lvm/.python311-venv/.official-ipex-llm-xpu/lib/python3.11/site-packages/ipex_llm/transformers/low_bit_linear.py :729
`x_2d = x.view(-1, x_shape[-1]) `

If I modify as: `x_2d = x.contiguous().view(-1, x_shape[-1])`, everything will be OK.
I think the issue is related to LLaVA model's vision_feature_select_strategy (`vision_feature_select_strategy=default`) which may make the tensor discontiguous.

Can anyone help on this issue? Thanks!

**Python packages:**
ipex-llm                      2.2.0b20241011
transformers                  4.45.2

**Comment by Oscilloscope98** [comment]
Hi @Johere, we are reproducing this issue. We will update here for any progress :)

**Comment by JinheTang** [comment]
Hi @Johere , we have updated our llava example in our latest ipex-llm. please follow the instructions in the [latest llava example](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/PyTorch-Models/Model/llava) to see if it works. If the issue continues, could you please share the scripts you're using to run the multi-turn chat, along with the output from our [env-check scripts](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts), to help us gather more details?

**Comment by Johere** [comment]
> Hi @Johere , we have updated our llava example for `llava-hf/llava-1.5-7b-hf`. Please follow the instructions in the [latest llava example](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/PyTorch-Models/Model/llava) to see if it works.
> 
> If the issue continues, could you please share the scripts you're using to run the multi-turn chat, along with the output from our [env-check scripts](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/scripts), to help us gather more details? :)

Hi @JinheTang  Thanks for your reply. The problem still exists. To reproduce the problem I met, please modify several lines of the [latest llava example](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/PyTorch-Models/Model/llava):
```
diff --git a/python/llm/example/GPU/PyTorch-Models/Model/llava/generate.py b/python/llm/example/GPU/PyTorch-Models/Model/llava/generate.py
index b70e22541a..57a4f0e98c 100644
--- a/python/llm/example/GPU/PyTorch-Models/Model/llava/generate.py
+++ b/python/llm/example/GPU/PyTorch-Models/Model/llava/generate.py
@@ -65,7 +65,18 @@ if __name__ == '__main__':
     else:
        image = Image.open(requests.get(image_path, stream=True).raw)

-    inputs = processor(text=text, images=image, return_tensors="pt").to('xpu')
+    # inputs = processor(text=text, images=image, return_tensors="pt").to('xpu')
+    # multi-image chat debug
+    image_2 = Image.open(requests.get("http://farm5.staticflickr.com/4031/4440753665_631134eaa4_z.jpg", stream=True).raw)
+    messages.append(
+        {
+            "role": "user",
+            "content": [
+                {"type": "image"},
+                {"type": "text", "text": prompt}
+            ]
+        })
+    inputs = processor(text=text, images=[image, image_2], return_tensors="pt").to('xpu')

```
Env check output log is attached:
[env-check.txt](https://github.com/user-attachments/files/17627863/env-check.txt)

**Comment by JinheTang** [comment]
Hi @Johere , thanks for the script, we will try to reproduce it.

**Comment by JinheTang** [comment]
Hi @Johere , we have reproduced the issue. If there's any update we will let you know.

**Comment by Oscilloscope98** [comment]
Hi @Johere,

Sorry for the late reply. We have fixed this bug in `ipex-llm>=2.2.0b20241113`. You could have a try with latest `ipex-llm` :)

Please let us know for any further problems.
