### ISSUE TITLE
A770 run harness.RuntimeError: unsupported dtype, only fp32 and fp16 are supported

### ISSUE THREAD

**Issue by tao-ov** [intel-analytics/ipex-llm#12304]
(llm) test@test-Z590-VISION-D:~/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness$ python run_llb.py --model ipex-llm --pretrained /home/test/models/LLM/baichuan2-7b/pytorch/ --precision sym_int4 --device xpu --tasks winogrande --batch 1 --no_cache
/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-10-31 14:44:27,844 - INFO - intel_extension_for_pytorch auto imported
Selected Tasks: ['winogrande']
The repository for /home/test/models/LLM/baichuan2-7b/pytorch/ contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//home/test/models/LLM/baichuan2-7b/pytorch/.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
2024-10-31 14:44:30,657 - WARNING - Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
2024-10-31 14:44:39,311 - INFO - Converting the current model to sym_int4 format......
Downloading builder script: 5.65kB [00:00, 7.26MB/s]
Downloading readme: 9.97kB [00:00, 14.1MB/s]
Downloading data: 100%|█████████████████████████████████████████████████| 3.40M/3.40M [00:19<00:00, 172kB/s]
Generating train split: 100%|███████████████████████████████| 40398/40398 [00:00<00:00, 69234.88 examples/s]
Generating test split: 100%|██████████████████████████████████| 1767/1767 [00:00<00:00, 69010.06 examples/s]
Generating validation split: 100%|████████████████████████████| 1267/1267 [00:00<00:00, 67524.56 examples/s]
Task: winogrande; number of docs: 1267
Task: winogrande; document 0; context prompt (starting on next line):
Natalie took basic French lessons from Betty after school because Betty is strong at that language.

My friends tried to drive the car through the alleyway but the car was too wide.

Sarah didn't practice ballet much but Mary practiced all the time. Sarah wasn't chosen to be a lead dancer.

The trainer tried to put the exercise equipment in the van but it wouldn't fit; the van was too small.

Natalie never checks the air in the tires while Tanya does and you just knew Natalie would have flat tires.

People think Rebecca
(end of prompt on previous line)
Requests: [Req_loglikelihood("Natalie took basic French lessons from Betty after school because Betty is strong at that language.\n\nMy friends tried to drive the car through the alleyway but the car was too wide.\n\nSarah didn't practice ballet much but Mary practiced all the time. Sarah wasn't chosen to be a lead dancer.\n\nThe trainer tried to put the exercise equipment in the van but it wouldn't fit; the van was too small.\n\nNatalie never checks the air in the tires while Tanya does and you just knew Natalie would have flat tires.\n\nPeople think Samantha", ' is embarassed, because Samantha made snide comments about the shirt Rebecca was wearing.')[0]
, Req_loglikelihood("Natalie took basic French lessons from Betty after school because Betty is strong at that language.\n\nMy friends tried to drive the car through the alleyway but the car was too wide.\n\nSarah didn't practice ballet much but Mary practiced all the time. Sarah wasn't chosen to be a lead dancer.\n\nThe trainer tried to put the exercise equipment in the van but it wouldn't fit; the van was too small.\n\nNatalie never checks the air in the tires while Tanya does and you just knew Natalie would have flat tires.\n\nPeople think Rebecca", ' is embarassed, because Samantha made snide comments about the shirt Rebecca was wearing.')[0]
]
Running loglikelihood requests
  0%|                                                                              | 0/2534 [00:00<?, ?it/s]/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/models/utils.py:79: UserWarning: `BIGDL_QUANTIZE_KV_CACHE` is deprecated and will be removed in future releases. Please use `IPEX_LLM_QUANTIZE_KV_CACHE` instead.
  warnings.warn(
  0%|                                                                              | 0/2534 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/run_llb.py", line 147, in <module>
    main()
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/run_llb.py", line 101, in main
    results = evaluator.simple_evaluate(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/utils.py", line 243, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/evaluator.py", line 94, in simple_evaluate
    results = evaluate(
              ^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/utils.py", line 243, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/evaluator.py", line 289, in evaluate
    resps = getattr(lm, reqtype)([req.args for req in reqs])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/base.py", line 221, in loglikelihood
    return self._loglikelihood_tokens(new_reqs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/base.py", line 357, in _loglikelihood_tokens
    self._model_call(batched_inps), dim=-1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/ipexllm_whowhat/ipex-llm/python/llm/dev/benchmark/harness/lm-evaluation-harness/lm_eval/models/huggingface.py", line 514, in _model_call
    return self.model(inputs)["logits"]
           ^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 686, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/models/baichuan.py", line 198, in baichuan_model_7b_forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/.cache/huggingface/modules/transformers_modules/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniforge3/envs/llm/lib/python3.11/site-packages/ipex_llm/transformers/models/baichuan.py", line 271, in baichuan_attention_forward_7b
    xe_addons.rotary_half_inplaced(self.rotary_emb.inv_freq, position_ids,
RuntimeError: unsupported dtype, only fp32 and fp16 are supported

**Comment by cranechu0131** [comment]
Hi tao-ov,

We have reproduced the issue and we are looking into it. We'll update if there's any solution.

**Comment by cranechu0131** [comment]
Hi tao-ov,

We have found a tentative solution to this issue. Please change the function in `<path to your ipex-llm package source code>/transformers/models/utils.py` line 163 to the following one:

```python
def should_use_fuse_rope(hidden_states, position_ids, training):
    return (
        hidden_states.dtype in [torch.float, torch.half]
        and hidden_states.device.type == "xpu"
        and not training and not hidden_states.requires_grad
        and position_ids is not None
    )
```

This ought to solve the issue. Meanwhile, we are looking for a perminent solution to this issue.

**Comment by cranechu0131** [comment]
Hi tao-ov,

We have found another convenient solution to this issue. Please switch harness command to the following one:

```
python run_llb.py --model ipex-llm --pretrained /home/test/models/LLM/baichuan2-7b/pytorch/ --precision sym_int4 --device xpu --tasks winogrande --batch 1 --no_cache --model_args dtype=float16
```

**Comment by tao-ov** [comment]
yes, this command add --model_args dtype=float16 it success, thanks for your supporting~
