### ISSUE TITLE
'AutoModel' object has no attribute 'config' when using Speech_Paraformer-Large on NPU

### ISSUE THREAD

**Issue by fanyhchn** [intel-analytics/ipex-llm#12412]
Traceback (most recent call last):
  File "D:\projects\ipex-llm\python\llm\example\NPU\HF-Transformers-AutoModels\Multimodal\speech_paraformer-large.py", line 44, in <module>
    model = AutoModel(
  File "D:\miniforge3\envs\llm_para\lib\site-packages\ipex_llm\transformers\npu_model.py", line 616, in __init__
    self.model = self.from_pretrained(*args, **kwargs)
  File "D:\miniforge3\envs\llm_para\lib\unittest\mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "D:\miniforge3\envs\llm_para\lib\site-packages\ipex_llm\transformers\npu_model.py", line 170, in from_pretrained
    model.config.update({"optimize_model": optimize_model})
AttributeError: 'AutoModel' object has no attribute 'config'

**Comment by sgwhat** [comment]
Hi @fanyhchn , we have identified your issue and are currently working on a fix. You may install the latest version of `ipex-llm[npu]` tomorrow to get the update.
