### ISSUE TITLE
vllm use docker intelanalytics/ipex-llm-serving-xpu:2.2.0-b7, ImportError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KiwiHana** [intel-analytics/ipex-llm#12515]
16G内存，500G磁盘，一张A770，13代core i7

1. ubuntu22.04安装oneapi 2024.1 base toolkit

2. docker pull intelanalytics/ipex-llm-serving-xpu:2.2.0-b7

3. docker run -itd --net=host --device=/dev/dri -v /opt:/opt -e no_proxy=localhost,127.0.0.1 --name=vllm_server_arc --shm-size="16g" intelanalytics/ipex-llm-serving-xpu:2.2.0-b7

4. docker start vllm_server_arc

5. docker exec -it vllm_server_arc bash

6. apt-get install jq

7. vim start_ Qwen2-7B-Instruct_serving.sh

配置内容：---------分割线 开始---------------

```
#!/bin/bash

model="/llm/models/Qwen2-7B-Instruct"

served_model_name="Qwen2-7B-Instruct"

export USE_XETLA=OFF



export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=1

export SYCL_CACHE_PERSISTENT=1

export TORCH_LLM_ALLREDUCE=0

export CCL_DG2_ALLREDUCE=1



# Tensor parallel related arguments:

export CCL_WORKER_COUNT=1

export FI_PROVIDER=shm

export CCL_ATL_TRANSPORT=ofi

export CCL_ZE_IPC_EXCHANGE=sockets

export CCL_ATL_SHM=1



source /opt/intel/1ccl-wks/setvars.sh



python -m ipex_llm.vllm.xpu.entrypoints.openai.api_server \

--served-model-name $served_model_name \

--port 8000 \

--model $model \

--trust-remote-code \

--gpu-memory-utilization 0.95 \

--device xpu \

--dtype float16 \

--enforce-eager \

--load-in-low-bit int4 \

--max-model-len 2048 \

--max-num-batched-tokens 4000 \

--tensor-parallel-size 1
```

--------------分割线 结束---------------
8. bash start_ Qwen2-7B-Instruct_serving.sh

==》 报错

报错内容：------------分割线 开始---------------

root@test-AI:/llm# bash start_ Qwen2-7B-Instruct_serving.sh

```
start_: line 18: /opt/intel/1ccl-wks/setvars.sh: No such file or directory

/usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?

 warn(

Traceback (most recent call last):

 File "<frozen runpy>", line 189, in _run_module_as_main

 File "<frozen runpy>", line 112, in _get_module_details

 File "/usr/local/lib/python3.11/dist-packages/ipex_llm/__init__.py", line 38, in <module>

   ipex_importer.import_ipex()

 File "/usr/local/lib/python3.11/dist-packages/ipex_llm/utils/ipex_importer.py", line 136, in import_ipex

   self.directly_import_ipex()

 File "/usr/local/lib/python3.11/dist-packages/ipex_llm/utils/ipex_importer.py", line 156, in directly_import_ipex

   import intel_extension_for_pytorch as ipex

 File "/usr/local/lib/python3.11/dist-packages/intel_extension_for_pytorch/__init__.py", line 95, in <module>

   from .utils._proxy_module import *

 File "/usr/local/lib/python3.11/dist-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>

   import intel_extension_for_pytorch._C

ImportError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory


```

------------------分割线 结束---------------

pip list 内容：

root@test-AI:/llm# pip list

```
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/oneccl_bind_pt-2.1.300+xpu-py3.11-linux-x86_64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

Package                          Version

--------------------------------- ----------------------

accelerate                       0.23.0

aiofiles                         23.2.1

aiohappyeyeballs                 2.4.3

aiohttp                          3.11.7

aiosignal                        1.3.1

annotated-types                  0.7.0

anyio                            4.6.2.post1

Arpeggio                         2.0.2

attrs                            24.2.0

bigdl-core-xe-21                 2.6.0b20241126

bigdl-core-xe-addons-21          2.6.0b20241126

bigdl-core-xe-batch-21           2.6.0b20241126

blinker                          1.4

caliper-reader                   0.4.1

certifi                          2024.8.30

charset-normalizer               3.4.0

click                            8.1.7

cloudpickle                      3.1.0

cmake                            3.31.1

colorama                         0.4.6

contourpy                        1.3.1

cryptography                     3.4.8

cycler                           0.12.1

datasets                         3.1.0

dbus-python                      1.2.18

dill                             0.3.8

diskcache                        5.6.3

distro                           1.7.0

einops                           0.8.0

fastapi                          0.112.4

ffmpy                            0.4.0

filelock                         3.16.1

fonttools                        4.55.0

frozenlist                       1.5.0

fschat                           0.2.36

fsspec                           2024.9.0

gguf                             0.10.0

gradio                           4.43.0

gradio_client                    1.3.0

h11                              0.14.0

httpcore                         1.0.7

httplib2                         0.20.2

httptools                        0.6.4

httpx                            0.27.2

huggingface-hub                  0.26.2

idna                             3.10

importlib-metadata               4.6.4

importlib_resources              6.4.5

intel-cmplr-lib-ur               2025.0.2

intel_extension_for_pytorch      2.1.30.post0

intel-openmp                     2025.0.2

interegular                      0.3.3

ipex-llm                         2.2.0b20241126

jeepney                          0.7.1

Jinja2                           3.1.4

jiter                            0.7.1

jsonschema                       4.23.0

jsonschema-specifications        2024.10.1

keyring                          23.5.0

kiwisolver                       1.4.7

lark                             1.2.2

latex2mathml                     3.77.0

launchpadlib                     1.10.16

lazr.restfulclient               0.14.4

lazr.uri                         1.0.6

llnl-hatchet                     2024.1.3

llvmlite                         0.43.0

lm-format-enforcer               0.10.6

markdown-it-py                   3.0.0

markdown2                        2.5.1

MarkupSafe                       2.1.5

matplotlib                       3.9.2

mdurl                            0.1.2

mistral_common                   1.5.1

modelscope                       1.21.0

more-itertools                   8.10.0

mpi4py                           4.0.1

mpmath                           1.3.0

msgpack                          1.1.0

msgspec                          0.18.6

multidict                        6.1.0

multiprocess                     0.70.16

nest-asyncio                     1.6.0

networkx                         3.4.2

nh3                              0.2.18

numba                            0.60.0

numpy                            1.26.4

oauthlib                         3.2.0

oneccl-bind-pt                   2.1.300+xpu

oneccl-bind-pt                   2.1.300+xpu

openai                           1.55.1

orjson                           3.10.12

outlines                         0.0.46

packaging                        24.2

pandas                           2.2.3

partial-json-parser              0.2.1.1.post4

peft                             0.13.2

pillow                           10.4.0

pip                              24.3.1

prometheus_client                0.21.0

prometheus-fastapi-instrumentator 7.0.0

prompt_toolkit                   3.0.48

propcache                        0.2.0

protobuf                         5.29.0rc3

psutil                           6.1.0

py-cpuinfo                       9.0.0

pyairports                       2.1.1

pyarrow                          18.1.0

pycountry                        24.6.1

pydantic                         2.10.2

pydantic_core                    2.27.1

pydot                            3.0.2

pydub                            0.25.1

Pygments                         2.18.0

PyGObject                        3.42.1

PyJWT                            2.3.0

pyparsing                        3.2.0

python-apt                       2.4.0+ubuntu3

python-dateutil                  2.9.0.post0

python-dotenv                    1.0.1

python-multipart                 0.0.12

pytz                             2024.2

PyYAML                           6.0.2

pyzmq                            26.2.0

ray                              2.39.0

referencing                      0.35.1

regex                            2024.11.6

requests                         2.32.3

rich                             13.9.4

rpds-py                          0.21.0

ruff                             0.8.0

safehttpx                        0.1.1

safetensors                      0.4.6.dev0

SecretStorage                    3.3.1

semantic-version                 2.10.0

sentencepiece                    0.2.0

setuptools                       59.6.0

setuptools-scm                   8.1.0

shellingham                      1.5.4

shortuuid                        1.0.13

six                              1.16.0

sniffio                          1.3.1

starlette                        0.38.6

svgwrite                         1.4.3

sympy                            1.13.3

tabulate                         0.9.0

tcmlib                           1.2.0

textX                            4.1.0

tiktoken                         0.7.0

tokenizers                       0.20.3

tomlkit                          0.12.0

torch                            2.1.0.post2+cxx11.abi

torchaudio                       2.1.0.post2+cxx11.abi

torchvision                      0.16.0.post2+cxx11.abi

tqdm                             4.67.1

transformers                     4.46.3

transformers-stream-generator    0.0.5

triton-xpu                       3.0.0b2

typer                            0.13.1

typing_extensions                4.12.2

tzdata                           2024.2

umf                              0.9.1

urllib3                          2.2.3

uvicorn                          0.32.1

uvloop                           0.21.0

vllm                             0.6.2+ipexllm.xpu

wadllib                          1.3.6

watchfiles                       1.0.0

wavedrom                         2.0.3.post3

wcwidth                          0.2.13

websockets                       12.0

wheel                            0.37.1

xxhash                           3.5.0

yarl                             1.18.0

zipp                             1.0.0
```

**Comment by gc-fu** [comment]
You need to `source /opt/intel/oneapi/setvars.sh`

**Comment by KiwiHana** [comment]
docker run -itd --net=host --device=/dev/dri -v /opt:/opt -e no_proxy=localhost,127.0.0.1 --name=vllm_server_arc --shm-size="16g" intelanalytics/ipex-llm-serving-xpu:2.2.0-b7

在容器里，没有/opt/intel 这个文件夹。

**Comment by gc-fu** [comment]
Try mount your opt directory to another different position:

`-v /opt:/opt`

**Comment by KiwiHana** [comment]
> Try mount your opt directory to another different position:
> 
> Change `-v /opt:/opt` to `-v /opt:ANOTHER_LOCATION`

Yes, solved it!

顺便问一下使用的模型支持.safetersons格式吗？还是只支持 .bin格式呢？

**Comment by gc-fu** [comment]
应该都支持的
