### ISSUE TITLE
[LLM ON SPR] failed to inference of Qwen-7B-Chat on SPR, w/ BenchmarkWrapper

### ISSUE THREAD

**Issue by intelyoungway** [intel-analytics/ipex-llm#9493]
Model: Qwen-7B-Chat
Quant: Q4_0
BigDL-LLM: 2.4.0
BigDL-Nano: 2.4.0
transformers: 4.31.0
CPU SKU: 1S-SPR8468V (Quadrant), allocate only 1socket (0-47, memory-bind 0) to docker
memory: DDR5 (not try HBM yet)
cmdline:
``` bash
  source bigdl-llm-init -t
  export OMP_THREAD_NUM=12
  numactl -C 0-11 -m 0 python generate.py --prompt="`cat prompt_1k.txt`" # 1K token input
```

script:
  ```python
  import torch
  import time
  import argparse
  import numpy as np
   
  from bigdl.llm.transformers import AutoModelForCausalLM
  from bigdl.llm.transformers import AutoModelForCausalLM
  from transformers import AutoTokenizer
  from benchmark_util import BenchmarkWrapper as bw
   
  # you could tune the prompt based on your own model
  QWEN_PROMPT_FORMAT = "{prompt}"
   
  if __name__ == '__main__':
      parser = argparse.ArgumentParser(description='Predict Tokens using `generate()` API for Qwen model')
      parser.add_argument('--repo-id-or-model-path', type=str, default="/weights/Qwen-7B-Chat",
                          help='The huggingface repo id for the Qwen model to be downloaded'
                               ', or the path to the huggingface checkpoint folder')
      parser.add_argument('--prompt', type=str, default="AI是什么?",
                          help='Prompt to infer')
      parser.add_argument('--n-predict', type=int, default=512,
                          help='Max tokens to predict')
      parser.add_argument('--warmup', type=int, default=2)
   
      args = parser.parse_args()
      model_path = args.repo_id_or_model_path
   
      # Load model in 4 bit,
      # which convert the relevant layers in the model into INT4 format
      model = AutoModelForCausalLM.from_pretrained(model_path,
                                                   load_in_4bit=True,
                                                   trust_remote_code=True)
      model = bw(model, do_print=True)
      # Load tokenizer
      tokenizer = AutoTokenizer.from_pretrained(model_path,
                                                trust_remote_code=True)
   
      # Generate predicted tokens
      with torch.inference_mode():
          prompt = QWEN_PROMPT_FORMAT.format(prompt=args.prompt)
          input_ids = tokenizer.encode(prompt, return_tensors="pt")
          for i in range(args.warmup+1):
            st = time.time()
            print(input_ids)
            output = model.generate(input_ids,
                                  max_new_tokens=args.n_predict)
            end = time.time()
          output_str = tokenizer.decode(output[0], skip_special_tokens=True)
          n_input = len(input_ids[0])
          n_output = len(output[0])-n_input
          print(f'Inference time: {end-st} s')
          print(f'input_len={n_input} tokens')
          print(f'output_len={n_output} tokens')
          print('-'*20, 'Output', '-'*20)
          print(output_str)
  ```
Model config:
  ```json
  {
    "architectures": [
      "QWenLMHeadModel"
    ],
    "auto_map": {
      "AutoConfig": "configuration_qwen.QWenConfig",
      "AutoModelForCausalLM": "modeling_qwen.QWenLMHeadModel"
    },
    "attn_dropout_prob": 0.0,
    "bf16": false,
    "emb_dropout_prob": 0.0,
    "fp16": false,
    "fp32": false,
    "hidden_size": 4096,
    "intermediate_size": 22016,
    "initializer_range": 0.02,
    "kv_channels": 128,
    "layer_norm_epsilon": 1e-06,
    "max_position_embeddings": 8192,
    "model_type": "qwen",
    "no_bias": true,
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "onnx_safe": null,
    "rotary_emb_base": 10000,
    "rotary_pct": 1.0,
    "scale_attn_weights": true,
    "seq_length": 8192,
    "tie_word_embeddings": false,
    "tokenizer_class": "QWenTokenizer",
    "transformers_version": "4.32.0",
    "use_cache": true,
    "use_dynamic_ntk": true,
    "use_flash_attn": "auto",
    "use_logn_attn": true,
    "vocab_size": 151936
  }
  ```

issue:
  Inference failed with the following error message:
  ```bash
  Traceback (most recent call last):
    File "/root/qwen/generate.py", line 60, in <module>
      output = model.generate(input_ids,
    File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
      return func(*args, **kwargs)
    File "/root/qwen/benchmark_util.py", line 1611, in generate
      return self.sample(
    File "/root/qwen/benchmark_util.py", line 2682, in sample
      outputs = self(
    File "/root/qwen/benchmark_util.py", line 531, in __call__
      return self.model(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
      return forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1058, in forward
      transformer_outputs = self.transformer(
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
      return forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 889, in forward
      outputs = block(
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
      return forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 609, in forward
      attn_outputs = self.attn(
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
      return self._call_impl(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
      return forward_call(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/bigdl/llm/transformers/models/qwen.py", line 189, in qwen_attention_forward
      attn_output, attn_weight = self._attn(
    File "/root/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 349, in _attn
      causal_mask = registered_causal_mask[
  TypeError: 'NoneType' object is not subscriptable
  ```
  
target:
  enable inference with HF-Model API on BigDL-LLM for SPR, support w/ benchmark_util.BenchmarkWrapper

related codes:
  https://github.com/intel-analytics/BigDL/blob/main/python/llm/example/CPU/HF-Transformers-AutoModels/Model/qwen/generate.py

**Comment by qiyuangong** [comment]
Thank you, @intelyoungway, for creating this issue! :)

We have reproduced this issue in the desktop & server environment with the latest downloaded `Qwen-7B-Chat`. 

It seems that Qwen updated `modeling_qwen.py` in https://huggingface.co/Qwen/Qwen-7B-Chat/commit/2abd8e5777bb4ce9c8ab4be7dbbd0fe4526db78d. This causes some inconsistency in `generalization`.

We will try to fix it ASAP. :)

As a hotfix, you can replace `modeling_qwen.py` with the older version (https://huggingface.co/Qwen/Qwen-7B-Chat/tree/8857f7754f11d6b5b9d8f3b4fbff416fc102ed30). That will also fix this example.

**Comment by qiyuangong** [comment]
Issue fixed by #9513. @intelyoungway 
Please try latest nightly build tomorrow.

**Comment by qiyuangong** [comment]
Latest nightly build can be download with 
```
pip install bigdl-llm --pre
```

Or you can download latest whe from https://pypi.org/project/bigdl-llm/#history

**Comment by intelyoungway** [comment]
Sorry I just review and found the fixation. Still many thanks to qiyuan! I think we can close it.
